### PR TITLE
ORC-1219: Remove redundant `toString`

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to clean up redundant `toString` invocation style.

ORC-1219 will be assigned to @deadwind4 .

### Why are the changes needed?

Simple clean ups.

### How was this patch tested?

Pass the CIs.

Closes #1181

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @williamhyun , too

**Comment by dongjoon-hyun** [comment]
cc @deadwind4

**Comment by guiyanakuang** [comment]
+1 LGTM
If using intellij there is a little trick that might help. : )
Menu:  Code -> Analyze Code -> Run Inspection by name
Paste any warning message, this helps to find all similar warnings in the specified range.
image

**Review by deadwind4 — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Yes, @guiyanakuang , I used that to validate https://github.com/apache/orc/pull/1181 's completeness and found that it was incomplete patch.

**Review by williamhyun — APPROVED** [review]
+1 LGTM

**Comment by williamhyun** [comment]
Merged to main. 
Thank you @deadwind4, @dongjoon-hyun, and @guiyanakuang

**Comment by dongjoon-hyun** [comment]
Thank you, @deadwind4 , @guiyanakuang , @williamhyun !

**Pull request closed without merging**
