### PR TITLE
ORC-1278: Update cmake docs version to 3.12

### PR DESCRIPTION
**Pull request by deshanxiao**
### What changes were proposed in this pull request?
This PR aims to add a cmake build version in [README.md](https://github.com/apache/orc/blob/main/README.md)

### Why are the changes needed?
[add_compile_definitions ](https://cmake.org/cmake/help/latest/command/add_compile_definitions.html)only supprt cmake 3.12+. We can update the docs [README.md](https://github.com/apache/orc/blob/main/README.md)

In ubuntu 18.04:

> sudo apt install cmake

> make ..

we will get an error:

CMake Error at CMakeLists.txt:147 (add_compile_definitions):
  Unknown CMake command "add_compile_definitions".

### CODE REVIEW

**Comment by deshanxiao** [comment]
CC @dongjoon-hyun @williamhyun and @guiyanakuang

**Review by guiyanakuang — APPROVED** [review]
LGTM

**Comment by guiyanakuang** [comment]
Merged to main

**Comment by guiyanakuang** [comment]
Welcome to the Apache ORC community. What is your JIRA ID, @deshanxiao ?

**Comment by deshanxiao** [comment]
Thank you @guiyanakuang !

**Review by dongjoon-hyun — COMMENTED** [review]
Actually, we need to update the following together, @deshanxiao and @guiyanakuang . Could you make a followup PR?

https://github.com/apache/orc/blob/541b54398d80b0fcdcc9f4c523b52c5eebd96a16/CMakeLists.txt#L13

**Review by dongjoon-hyun — COMMENTED** [review]
To help this PR, we need to drop `Ubuntu 18` support. I'm not sure `add_compile_definitions` is worth to drop it, but we can discuss here.
```
$ docker run -it --rm apache/orc-dev:ubuntu18 cmake --version | head -n1
cmake version 3.10.2
```

WDYT, @williamhyun , @wgtmac , @guiyanakuang , @stiga-huang ?

**Comment by dongjoon-hyun** [comment]
To be clear, this is for Apache ORC 1.9 whose release date is `September 15, 2023`.

**Comment by deshanxiao** [comment]
> Actually, we need to update the following together, @deshanxiao and @guiyanakuang . Could you make a followup PR?
> 
> https://github.com/apache/orc/blob/541b54398d80b0fcdcc9f4c523b52c5eebd96a16/CMakeLists.txt#L13

@dongjoon-hyun Thank you~ Will make a followup PR.

**Comment by wgtmac** [comment]
> To help this PR, we need to drop `Ubuntu 18` support. I'm not sure `add_compile_definitions` is worth to drop it, but we can discuss here.
> 
> ```
> $ docker run -it --rm apache/orc-dev:ubuntu18 cmake --version | head -n1
> cmake version 3.10.2
> ```
> 
> WDYT, @williamhyun , @wgtmac , @guiyanakuang , @stiga-huang ?

Ubuntu 18.04 is still far from its EOL date. Should we update the docker file to download & install CMake 3.12?

**Comment by deshanxiao** [comment]
> To help this PR, we need to drop `Ubuntu 18` support. I'm not sure `add_compile_definitions` is worth to drop it, but we can discuss here.
> 
> ```
> $ docker run -it --rm apache/orc-dev:ubuntu18 cmake --version | head -n1
> cmake version 3.10.2
> ```
> 
> WDYT, @williamhyun , @wgtmac , @guiyanakuang , @stiga-huang ?

In CMake docs:
> Note This command has been superseded by alternatives:
Use [add_compile_definitions()](https://cmake.org/cmake/help/latest/command/add_compile_definitions.html#command:add_compile_definitions) to add preprocessor definitions.
Use [include_directories()](https://cmake.org/cmake/help/latest/command/include_directories.html#command:include_directories) to add include directories.
Use [add_compile_options()](https://cmake.org/cmake/help/latest/command/add_compile_options.html#command:add_compile_options) to add other options.

We could upgrade cmake, although the lower version of add_definitions can do the same thing, but it is deprecated by official. See https://cmake.org/cmake/help/latest/command/add_definitions.html?highlight=add_definitions

**Comment by dongjoon-hyun** [comment]
+1 for @wgtmac 's suggestion! Thanks.

**Comment by deshanxiao** [comment]
> > To help this PR, we need to drop `Ubuntu 18` support. I'm not sure `add_compile_definitions` is worth to drop it, but we can discuss here.
> > ```
> > $ docker run -it --rm apache/orc-dev:ubuntu18 cmake --version | head -n1
> > cmake version 3.10.2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > WDYT, @williamhyun , @wgtmac , @guiyanakuang , @stiga-huang ?
> 
> Ubuntu 18.04 is still far from its EOL date. Should we update the docker file to download & install CMake 3.12?

Thank you~ I will test all docker file and try to update it.

**Pull request merged**
