### PR TITLE
ORC-1518: Remove findbugs folders

### PR DESCRIPTION
**Pull request by deshanxiao**
### What changes were proposed in this pull request?
This PR is aimed to remove findbugs folders since findbugs has been removed in [ORC-1269](https://issues.apache.org/jira/browse/ORC-1269).

### Why are the changes needed?
Remove redundant files.

### How was this patch tested?
N/A

### CODE REVIEW

**Comment by deshanxiao** [comment]
cc @dongjoon-hyun @williamhyun

**Review by mystic-lama — APPROVED** [review]
+1 LGTM

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @deshanxiao and @mystic-lama .

**Comment by dongjoon-hyun** [comment]
Also, cc @williamhyun

**Pull request closed without merging**
