### PR TITLE
ORC-691: Remove unused Snapcraft-related code

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to remove unused `Snapcraft`-related code from Apache ORC repository at Apache ORC 1.8.0.

### Why are the changes needed?

The last release was Apache ORC 1.5.2 on `7 August 2018`. We had better remove this from Apache ORC repo and Snapstore officially to reduce the confusion.
- https://snapcraft.io/orc

### How was this patch tested?

N/A (This is a removal of unused code)

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @omalley , @wgtmac , @pgaref , @williamhyun . WDYT about this removal?

**Comment by williamhyun** [comment]
+1 LGTM

**Comment by dongjoon-hyun** [comment]
Thank you, @williamhyun !

**Comment by wgtmac** [comment]
Just curious if we can get the user activity from snapcraft. If it is rarely used there, we are confident to deprecate the support.

**Comment by dongjoon-hyun** [comment]
Thank you for review. Ya, I'm also wondering if that is used until now, @wgtmac . 

@omalley may get some statistics as the owner of that Snapcraft store.

BTW, it's already not supported for three years (August 2018). To be safe, we may just want to remove this from our repo and keep `Snapcraft` store AS-IS status without any change.

**Comment by dongjoon-hyun** [comment]
Thank you, @williamhyun and @wgtmac . 
Since this PR only removes our unused code base, I'll merge this PR to `main` for Apache ORC 1.8.0.

**Pull request merged**
