### PR TITLE
ORC-863: Upgrade TravisCI from xenial to focal

### PR DESCRIPTION
**Pull request by williamhyun**
### What changes were proposed in this pull request?
This PR aims to upgrade TravisCI from xenial to focal. 

### Why are the changes needed?
Ubuntu 16 (Xenial) is dropped from ORC. 

### How was this patch tested?
Pass the TravisCI.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you for working on this, @williamhyun .

According to TravisCI doc, we need to update the following
- https://docs.travis-ci.com/user/reference/focal/
```
clang | 7.0.0
llvm | 10.0.0
```

**Comment by dongjoon-hyun** [comment]
Oh, according to the JVM failure, Java 8 is not supported there.
```
Ignoring license option: GPL -- using GPLv2+CE by default
install-jdk.sh 2020-06-02
Expected feature release number in range of 9 to 18, but got: 8
The command "~/bin/install-jdk.sh --target "/home/travis/openjdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "GPL" --cacerts" failed and exited with 3 during .
```

**Comment by williamhyun** [comment]
Thank you, I will convert the PR.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. TravisCI passed. Thanks!
Merged to main.

**Comment by dongjoon-hyun** [comment]
I also landed to branch-1.7 for Apache ORC 1.7.

**Comment by williamhyun** [comment]
Thank you!

**Pull request merged**
