### PR TITLE
[Won't Do] ORC-1381: Update .gitignore

### PR DESCRIPTION
**Pull request by deshanxiao**
### What changes were proposed in this pull request?
This PR aims to update `.gitignore`.
After this PR, we will exclude all `orc `and `crc `files in git except:
- ORC Files located in `examples `folder.
- All java resources test orc files.

### Why are the changes needed?
To exclude the git file impact caused by the example orc file like `my-file.orc`.

### How was this patch tested?
manual testing.

### CODE REVIEW

**Comment by deshanxiao** [comment]
```
find . -name "*.orc"
```
```
./my-file.orc
./java/core/src/test/resources/orc_split_elim.orc
./java/core/src/test/resources/col.dot.orc
./java/core/src/test/resources/orc-file-dst-no-timezone.orc
./java/core/src/test/resources/orc-file-no-timezone.orc
./java/core/src/test/resources/orc-file-11-format.orc
./java/core/target/test-classes/orc_split_elim.orc
./java/core/target/test-classes/col.dot.orc
./java/core/target/test-classes/orc-file-dst-no-timezone.orc
./java/core/target/test-classes/orc-file-no-timezone.orc
./java/core/target/test-classes/orc-file-11-format.orc
./java/mapreduce/src/test/resources/acid5k.orc
./java/mapreduce/src/test/resources/aaa.orc
./java/mapreduce/target/test-classes/acid5k.orc
./examples/TestOrcFile.testWithoutIndex.orc
./examples/orc_split_elim.orc
./examples/TestOrcFile.testUnionAndTimestamp.orc
./examples/TestOrcFile.testMemoryManagementV11.orc
./examples/TestStringDictionary.testRowIndex.orc
./examples/complextypes_iceberg.orc
./examples/bad_bloom_filter_1.6.11.orc
./examples/TestOrcFile.testStringAndBinaryStatistics.orc
./examples/orc_split_elim_cpp.orc
./examples/orc_split_elim_new.orc
./examples/TestOrcFile.testDate1900.orc
./examples/TestOrcFile.test1.orc
./examples/orc_no_format.orc
./examples/TestOrcFile.columnProjection.orc
./examples/corrupt/missing_length_stream_in_string_dict.orc
./examples/corrupt/stripe_footer_bad_column_encodings.orc
./examples/corrupt/missing_blob_stream_in_string_dict.orc
./examples/corrupt/negative_dict_entry_lengths.orc
./examples/TestOrcFile.testSeek.orc
./examples/over1k_bloom.orc
./examples/TestVectorOrcFile.testLz4.orc
./examples/nulls-at-end-snappy.orc
./examples/TestOrcFile.testTimestamp.orc
./examples/TestOrcFile.emptyFile.orc
./examples/TestOrcFile.testSnappy.orc
./examples/orc_index_int_string.orc
./examples/TestOrcFile.metaData.orc
./examples/version1999.orc
./examples/TestOrcFile.testMemoryManagementV12.orc
./examples/bad_bloom_filter_1.6.0.orc
./examples/demo-11-none.orc
./examples/TestOrcFile.testSargSkipPickupGroupWithoutIndexJava.orc
./examples/TestOrcFile.testDate2038.orc
./examples/decimal.orc
./examples/TestOrcFile.testWithoutCompressionBlockSize.orc
./examples/demo-12-zlib.orc
./examples/TestOrcFile.testSargSkipPickupGroupWithoutIndexCPlusPlus.orc
./examples/decimal64_v2.orc
./examples/TestOrcFile.testPredicatePushdown.orc
./examples/zero.orc
./examples/decimal64_v2_cplusplus.orc
./examples/TestVectorOrcFile.testZstd.0.12.orc
./examples/encrypted/sample2.orc
./examples/encrypted/sample1.orc
./examples/orc-file-11-format.orc
./examples/TestOrcFile.testStripeLevelStats.orc
./examples/demo-11-zlib.orc
./examples/TestVectorOrcFile.testLzo.orc

```

**Comment by deshanxiao** [comment]
cc @guiyanakuang @dongjoon-hyun

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you for making a PR, but I'm not sure if this is a correct direction, @deshanxiao .
For `.crc`, it could be, but `.orc`? Could you elaborate on your pain point a little more?

**Comment by deshanxiao** [comment]
Sure, the reason for this is that when I run the ORC example, the newly generated ORC file is not ignored by git. Generally speaking, git tends to ignore these binary files and process text files as much as possible. But I found that we have a lot of orc files that need to be used by test. So I added them to the whitelist.

**Comment by deshanxiao** [comment]
I'm not sure if it's worth adding gitignore in this scenario. Do you have any good suggestions? @dongjoon-hyun

**Comment by deshanxiao** [comment]
> Yes, unfortunately, I'm reluctant to hide these files. If you don't mind, shall we close this as `Won't Do`?

Thank you @dongjoon-hyun .  Close the PR.

**Comment by dongjoon-hyun** [comment]
Thank you for your decision, @deshanxiao .

**Pull request closed without merging**
