### PR TITLE
MINOR: Add Yiqun Zhang and Huya Company to committers.md

### PR DESCRIPTION
**Pull request by guiyanakuang**
### What changes were proposed in this pull request?
This PR aims to add Yiqun Zhang and Huya Company to committers.md file.

### Why are the changes needed?
N/A

### How was this patch tested?
N/A

### CODE REVIEW

**Comment by guiyanakuang** [comment]
cc @dongjoon-hyun  : )

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. :)

**Comment by guiyanakuang** [comment]
@dongjoon-hyun, I can merge now, right.  First time merge feels cautious. 😃

**Comment by dongjoon-hyun** [comment]
Congratulation for your first merging, @guiyanakuang ! :)

**Comment by dongjoon-hyun** [comment]
I published this change.
- https://orc.apache.org/develop/committers

Screen Shot 2021-11-25 at 5 05 53 PM

**Comment by guiyanakuang** [comment]
@dongjoon-hyun, thank you very much for publishing the update!

**Pull request merged**
