### PR TITLE
ORC-718: Enable Checkstyle plugin and FileTabCharacter rule.

### PR DESCRIPTION
**Pull request by williamhyun**
### What changes were proposed in this pull request?

This PR aims to enable Checkstyle plugin and FileTabCharacter rule.

### Why are the changes needed?

This will be helpful to improve code quality. 
It would be great if we could enable this in GitHub action.

### How was this patch tested?

Manual
```
mvn checkstyle:check
```

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
Thank you, @williamhyun . This is super useful.
Recently, I also saw some tab chars in the PR. Please feel free to add `mvn checkstyle:check` to GitHub Action.

+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Also, cc @pgaref .

**Comment by williamhyun** [comment]
Thank you for merging, I also made [another related PR](https://github.com/apache/orc/pull/614) to improve the quality of code further.

For the following, I'll make a PR soon.
> Please feel free to add mvn checkstyle:check to GitHub Action.

**Comment by pgaref** [comment]
> Also, cc @pgaref .

Pretty useful stuff indeed! Thanks both!

**Pull request merged**
