### PR TITLE
ORC-503: Introduce Maven wrapper

### PR DESCRIPTION
**Pull request by yuokada**
https://issues.apache.org/jira/browse/ORC-503

### CODE REVIEW

**Comment by yuokada** [comment]
@omalley Could you take a look?

**Review by dongjoon-hyun — COMMENTED** [review]
Hi, @yuokada .
This seems to be a little outdate and intrusive (+627, -4) line.
I made an alternative PR, https://github.com/apache/orc/pull/566 .

**Comment by yuokada** [comment]
@dongjoon-hyun Thanks. I didn't know that the script exists.

> This file is a simplified version of Apache Spark mvn wrapper.

**Comment by dongjoon-hyun** [comment]
Thank you for your contribution, @yuokada . And, sorry for not accepting your proposal. I'll review more actively in the community.

**Pull request closed without merging**
