### PR TITLE
ORC-1070: Upgrade site docker image to use Ubuntu 20.04

### PR DESCRIPTION
**Pull request by williamhyun**
### What changes were proposed in this pull request?
This PR aims to upgrade the `site` docker image to use Ubuntu 20.04

### Why are the changes needed?
To migrate to the latest OS. 

### How was this patch tested?
Manually.

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.
Let me verify the generated result.

**Comment by dongjoon-hyun** [comment]
I tested this on Apple M1 Max laptop. It looks working. The generate pages look good to me. Thanks!
```
$ docker build -t orc-site --no-cache .
[+] Building 295.1s (17/17) FINISHED
 => [internal] load build definition from Dockerfile                                                                         0.4s
 => => transferring dockerfile: 1.43kB                                                                                       0.0s
 => [internal] load .dockerignore                                                                                            0.6s
 => => transferring context: 34B                                                                                             0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                                                              1.3s
 => [auth] library/ubuntu:pull token for registry-1.docker.io                                                                0.0s
 => CACHED [ 1/11] FROM docker.io/library/ubuntu:20.04@sha256:626ffe58f6e7566e00254b638eb7e0f3b11d4da9675088f4781a50ae288f3  0.0s
 => [internal] load build context                                                                                            0.4s
 => => transferring context: 112.83kB                                                                                        0.1s
 => [ 2/11] RUN ln -fs /usr/share/zoneinfo/America/Los_Angeles /etc/localtime                                                1.2s
 => [ 3/11] RUN apt-get update                                                                                               5.1s
 => [ 4/11] RUN apt-get install -y   g++   gcc   git   libssl-dev   libz-dev   make   ruby-dev   rubygems   tzdata         119.6s
 => [ 5/11] RUN gem install   bundler   liquid   listen   rouge                                                             15.5s
 => [ 6/11] RUN gem install jekyll -v 3.8.6                                                                                 18.9s
 => [ 7/11] RUN gem install github-pages                                                                                    65.8s
 => [ 8/11] RUN useradd -ms /bin/bash orc                                                                                    2.2s
 => [ 9/11] COPY . /home/orc/site                                                                                            0.9s
 => [10/11] RUN chown -R orc:orc /home/orc                                                                                  58.4s
 => [11/11] WORKDIR /home/orc/site                                                                                           0.8s
 => exporting to image                                                                                                       4.0s
 => => exporting layers                                                                                                      3.9s
 => => writing image sha256:7468918d2794a0810448cc2effa3e8795ec59e01d765cae7fab66bbc02eb1642                                 0.0s
 => => naming to docker.io/library/orc-site                                                                                  0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them

$ docker run -d --name orc-container -p 4000:4000 orc-site
c90cf6d617efb77b0000620b597f42bb0ef47d18c15312fdb9c187b890a48277

$ open http://localhost:4000
```

**Comment by dongjoon-hyun** [comment]
BTW, @williamhyun . While you are working on this, could you generate `Apache ORC 1.7.3` API doc and update https://github.com/apache/orc/tree/main/site/api directory? It will be a good exercise to become a release manager.

```
$ git diff | head -n15
diff --git a/api/apidocs/allclasses-frame.html b/api/apidocs/allclasses-frame.html
index 61cae41c..53659220 100644
--- a/api/apidocs/allclasses-frame.html
+++ b/api/apidocs/allclasses-frame.html
@@ -2,10 +2,10 @@
 <!-- NewPage -->
 <html lang="en">
 <head>
-<!-- Generated by javadoc (1.8.0_312) on Mon Dec 20 12:48:23 PST 2021 -->
+<!-- Generated by javadoc (1.8.0_302) on Sun Sep 19 14:30:01 PDT 2021 -->
 <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
-<title>All Classes (ORC Examples 1.7.2 API)</title>
-<meta name="date" content="2021-12-20">
+<title>All Classes (ORC Examples 1.7.0 API)</title>
+<meta name="date" content="2021-09-19">
```

**Comment by dongjoon-hyun** [comment]
Please note that I already published the API doc to our website at `asf-site` branch. I only didn't change it on `main` branch.
- https://orc.apache.org/api/orc-core/

**Comment by williamhyun** [comment]
Sure, I will try!

**Pull request merged**
