### PR TITLE
ORC-792: Upgrade commons-lang3 to 3.12.0

### PR DESCRIPTION
**Pull request by williamhyun**
### What changes were proposed in this pull request?
This PR aims to upgrade commons-lang3 to version 3.12.0.

### Why are the changes needed?
This will bring the following features and bug fixes. 
- https://commons.apache.org/proper/commons-lang/changes-report.html#a3.12.0
    - Add JavaVersion.JAVA_17

### How was this patch tested?

Pass the CIs.

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Ya, it looks a good progress for JDK 17. Thank you for keeping working on this area.
Oh, you can merge this, @williamhyun .

**Comment by dongjoon-hyun** [comment]
Do you have still an issue with GitHub account?

**Comment by williamhyun** [comment]
Thank you, I am still having a problem with merging via GitHub, but I used GitBox to merge.

**Comment by dongjoon-hyun** [comment]
Oh, got it.

**Comment by dongjoon-hyun** [comment]
After merging, you can resolve the corresponding JIRA issue.
- https://issues.apache.org/jira/browse/ORC-792

I resolved and assigned ORC-792 to you and backported this commit to `branch-1.6`.

**Pull request closed without merging**
