### PR TITLE
ORC-1301: [C++] Enforce C++17

### PR DESCRIPTION
**Pull request by wgtmac**
### What changes were proposed in this pull request?
Enforce the C++ library to use C++17 to compile.

### Why are the changes needed?
To keep up the pace of modern C++ standard and improve development efficiency.

### How was this patch tested?
Manual test on laptop. It requires all GitHub action checks to pass.

### CODE REVIEW

**Comment by wgtmac** [comment]
@dongjoon-hyun Do you know why we don't have a Github action for g++ on macos? I cannot make the build (gcc 12 with mac m1) happy even w/o this change.

**Comment by dongjoon-hyun** [comment]
MacOS has `g++` as an alias of Apple CLang, @wgtmac .
```
$ g++ --version
Apple clang version 14.0.0 (clang-1400.0.29.102)
Target: arm64-apple-darwin22.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by wgtmac** [comment]
> MacOS has `g++` as an alias of Apple CLang, @wgtmac .
> 
> ```
> $ g++ --version
> Apple clang version 14.0.0 (clang-1400.0.29.102)
> Target: arm64-apple-darwin22.1.0
> Thread model: posix
> InstalledDir: /Library/Developer/CommandLineTools/usr/bin
> ```

Yes, I installed gcc from homebrew and set it explicitly like below:

`cmake .. -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_C_COMPILER=/opt/homebrew/Cellar/gcc/12.2.0/bin/gcc-12 -DCMAKE_CXX_COMPILER=/opt/homebrew/Cellar/gcc/12.2.0/bin/g++-12 -DBUILD_JAVA=OFF -DBUILD_LIBHDFSPP=OFF `

**Comment by dongjoon-hyun** [comment]
For Windows, we may want to upgrade to use `windows-2022` GitHub Action instead of `windows-2019` before this PR.

**Comment by dongjoon-hyun** [comment]
BTW, Windows CI is not working yet.
```
Directory: D:\a\orc\orc
...
No tests were found!!!
```

**Comment by dongjoon-hyun** [comment]
https://github.com/apache/orc/pull/1298 is merged. Could you rebase this PR?

**Comment by dongjoon-hyun** [comment]
https://github.com/apache/orc/pull/1297 is merged too.

**Comment by wgtmac** [comment]
> #1297 is merged too.

Thanks @dongjoon-hyun !

All the checks pass finally, please take a look.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. It's really great, @wgtmac .

**Comment by dongjoon-hyun** [comment]
Merged to main for Apache ORC 1.9.

**Pull request closed without merging**
