### PR TITLE
ORC-1278: [FOLLOWUP] Update cmake requirement to 3.12

### PR DESCRIPTION
**Pull request by deshanxiao**
### What changes were proposed in this pull request?
This is a followup pr for  [ORC-1278](https://github.com/apache/orc/pull/1258#issue-1378943057)
We adjusted the minimum version requirements for cmake.

### Why are the changes needed?
At present, it is impossible to build using cmake version below 3.12. We should update it.

### How was this patch tested?
build with cmake 3.12 and pass.

### CODE REVIEW

**Comment by deshanxiao** [comment]
image

**Comment by deshanxiao** [comment]
image

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @deshanxiao .
We are going to adjust Ubuntu18 Docker image later according to this PR.

**Comment by dongjoon-hyun** [comment]
Oh, it seems that this PR causes CMake failures on all MacOSes.
```
25 warnings and 18 errors generated.
make[2]: *** [c++/src/CMakeFiles/orc.dir/io/InputStream.cc.o] Error 1
make[1]: *** [c++/src/CMakeFiles/orc.dir/all] Error 2
make: *** [all] Error 2
Error: Process completed with exit code 2.
```

**Comment by dongjoon-hyun** [comment]
cc @guiyanakuang , @wgtmac , @williamhyun , too

**Comment by guiyanakuang** [comment]
https://github.com/apache/orc/blob/6a74eef74b8101c7396f196f1a27f5e124a005f6/CMakeLists.txt#L98-L106

The value of CMAKE_CXX_COMPILER_ID under 3.12 version is AppleClang.

It looks like we need to replace `CMAKE_CXX_COMPILER_ID STREQUAL "Clang"` with `${CMAKE_CXX_COMPILER_ID} MATCHES "Clang"`

**Comment by deshanxiao** [comment]
@guiyanakuang I am a little confused why modifying cmake_minimum_required will change CMAKE_CXX_COMPILER_ID. It looks well after your changes.

**Comment by guiyanakuang** [comment]
@deshanxiao. You can check out this cmake policy. 
> CMake 3.0 and above recognize that Apple Clang is a different compiler than upstream Clang and that they have different version numbers.

https://cmake.org/cmake/help/v3.0/policy/CMP0025.html#policy:CMP0025

**Comment by deshanxiao** [comment]
@guiyanakuang Get it, thank you~

**Comment by dongjoon-hyun** [comment]
Thank you, @guiyanakuang and @deshanxiao !
Merged to main for Apache ORC 1.9.0

**Pull request closed without merging**
