### PR TITLE
ORC-779: Upgrade commons-cli to 1.4

### PR DESCRIPTION
**Pull request by williamhyun**
### What changes were proposed in this pull request?

This PR aims to upgrade commons-cli to 1.4

### Why are the changes needed?

This will bring the latest bug fixes and improvements.

- http://commons.apache.org/proper/commons-cli/release_1_4.html 

### How was this patch tested?
Pass the CIs.

### CODE REVIEW

**Review by pgaref — APPROVED** [review]
+1 tests pending

**Comment by pgaref** [comment]
Thanks @williamhyun  ! Just merged this

**Comment by dongjoon-hyun** [comment]
+1, LGTM.
Thank you, @williamhyun and @pgaref .

**Comment by williamhyun** [comment]
Thank you @pgaref and @dongjoon-hyun !

**Comment by dongjoon-hyun** [comment]
Hi, @williamhyun and @pgaref .
I'll backport this to branch-1.6 for Apache ORC 1.6.8.

**Pull request merged**
