### PR TITLE
ORC-1433: [C++] Fix comment in the Vector.hh

### PR DESCRIPTION
**Pull request by wgtmac**
### What changes were proposed in this pull request?
There are some errors in the comment of Vector.hh

### Why are the changes needed?
Fix those errors.

### How was this patch tested?
Not required.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
This looks like worth to have a JIRA issue, @wgtmac . Could you make one?

**Review by guiyanakuang — APPROVED** [review]
+1 LGTM. Additionally, it seems that this fix should also be merged into the 1.9-branch. : )

**Comment by guiyanakuang** [comment]
Merged to main

**Review by dongjoon-hyun — COMMENTED** [review]
+1, LGTM, too.

**Pull request merged**
