### PR TITLE
ORC-836: StringGroupFromDoubleTreeReader Use Double toString

### PR DESCRIPTION
**Pull request by belugabehr**
### What changes were proposed in this pull request?
When converting from Double to String, use the Double class methods directly. Lower overhead of encoding by using ASCII.

### Why are the changes needed?
Performance.

### How was this patch tested?
No change in functionality.  Use existing unit tests.

### CODE REVIEW

**Comment by belugabehr** [comment]
@dongjoon-hyun This is a trivial one.  Can you please take a look? Thanks!

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you for pinging me, @belugabehr .
- The title looks wrong to me: `Use Long toString`. Do you want to say `Use Double.toString`?
- Could you check if we have more instances like this?

**Comment by belugabehr** [comment]
@dongjoon-hyun Thanks!!

You are correct, I meant to say "Double" instead of ~Long~

I changed the commit message.

All other instances correctly use the `toString` instead of `valueOf`, this was the only one.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you for confirming, @belugabehr .
Merged to main.

**Pull request merged**
