### PR TITLE
ORC-1174: Add `Ubuntu 22.04` to GitHub Action

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to add `Ubuntu 22.04` to GitHub Action.

### Why are the changes needed?

This will help the verification on the latest release.

Although [GitHub Action Virtual Environments](https://github.com/actions/virtual-environments) don't support `Ubuntu 22.04` officially yet, `Ubuntu 22.04` is available as `Public Beta`.

- https://github.com/actions/virtual-environments/issues/5490

### How was this patch tested?

Pass the GitHub Action on this PR.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
I'm looking at `rat` failure. It seems the one which was reported last vote by Prasanth.

**Comment by dongjoon-hyun** [comment]
Also, cc @prasanthj

**Comment by guiyanakuang** [comment]
+1, LGTM from my side.

**Comment by dongjoon-hyun** [comment]
Thank you, @guiyanakuang and @williamhyun !

**Comment by dongjoon-hyun** [comment]
For branch-1.7, I made the following backporting PR.
- https://github.com/apache/orc/pull/1128

**Pull request merged**
