### PR TITLE
ORC-1303: [C++] Upgrade GoogleTest to 1.12.1

### PR DESCRIPTION
**Pull request by wgtmac**
### What changes were proposed in this pull request?
Upgrade the gtest & gmock library to v1.12.1

### Why are the changes needed?
Prerequisite for C++17 adoption.

### How was this patch tested?
Pass the CI check.

### CODE REVIEW

**Comment by wgtmac** [comment]
@dongjoon-hyun @stiga-huang Can you please take a look? 

Without this change, I cannot upgrade the Github workflow of Windows build to adopt VS 2019/2022 and make the C++17 move.

**Review by stiga-huang — APPROVED** [review]
+1. LGTM

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
cc @williamhyun

**Comment by dongjoon-hyun** [comment]
Hi, @wgtmac and all. Unfortunately, this is reverted from `branch-1.8`.

https://github.com/apache/orc/commit/750e615091e399569e1f8a1c1491a5d2f343539c

`branch-1.8`'s CentOS7 and `Fedora37` was also tested during Apache ORC 1.8.0 release here (#1107) and this PR causes failures in `branch-1.8`.. After reverting it, the branch is recovered.

```
Test project /root/build
    Start 1: orc-test
1/8 Test #1: orc-test .........................   Passed    6.24 sec
    Start 2: java-test
2/8 Test #2: java-test ........................   Passed  213.58 sec
    Start 3: java-tools-test
3/8 Test #3: java-tools-test ..................   Passed    0.15 sec
    Start 4: java-bench-gen-test
4/8 Test #4: java-bench-gen-test ..............   Passed    1.54 sec
    Start 5: java-bench-scan-test
5/8 Test #5: java-bench-scan-test .............   Passed    1.30 sec
    Start 6: java-bench-hive-test
6/8 Test #6: java-bench-hive-test .............   Passed   14.21 sec
    Start 7: java-bench-spark-test
7/8 Test #7: java-bench-spark-test ............   Passed    5.14 sec
    Start 8: tool-test
8/8 Test #8: tool-test ........................   Passed   11.28 sec

100% tests passed, 0 tests failed out of 8

Total Test time (real) = 253.46 sec
Built target test-out
Finished fedora37 at Mon Nov 28 21:38:15 PST 2022
```

It was my bad to land #1298 to branch-1.8. I'll revert it to recover `branch-1.8` and prepare Apache ORC 1.8.1 vote.

**Comment by dongjoon-hyun** [comment]
Docker test is recovered.
```
$ ./run-all.sh apache branch-1.8

$ tail -n2 logs/*log
==> logs/centos7-test.log <==
Built target test-out
Finished centos7 at Mon Nov 28 22:32:44 PST 2022

==> logs/debian10-test.log <==
Built target test-out
Finished debian10 at Mon Nov 28 22:38:16 PST 2022

==> logs/debian10_jdk=11-test.log <==
Built target test-out
Finished debian10_jdk=11 at Mon Nov 28 22:41:52 PST 2022

==> logs/debian11-test.log <==
Built target test-out
Finished debian11 at Mon Nov 28 22:39:43 PST 2022

==> logs/fedora37-test.log <==
Built target test-out
Finished fedora37 at Mon Nov 28 22:39:08 PST 2022

==> logs/ubuntu18-test.log <==
Built target test-out
Finished ubuntu18 at Mon Nov 28 22:37:51 PST 2022

==> logs/ubuntu20-test.log <==
Built target test-out
Finished ubuntu20 at Mon Nov 28 22:42:01 PST 2022

==> logs/ubuntu20_jdk=11-test.log <==
Built target test-out
Finished ubuntu20_jdk=11 at Mon Nov 28 22:43:10 PST 2022

==> logs/ubuntu20_jdk=11_cc=clang-test.log <==
Built target test-out
Finished ubuntu20_jdk=11_cc=clang at Mon Nov 28 22:39:06 PST 2022

==> logs/ubuntu22-test.log <==
Built target test-out
Finished ubuntu22 at Mon Nov 28 22:40:22 PST 2022
```

**Pull request closed without merging**
