### PR TITLE
ORC-1645: [C++] Evaulate stripe stats before load stripe footer

### PR DESCRIPTION
**Pull request by Smith-Cruise**
### What changes were proposed in this pull request?

Stripe's stats are in the orc tail's metadata, which means we can evaluate stripe's stats before loading stripe's footer.

That can save one IO request.

https://issues.apache.org/jira/browse/ORC-1645

### Why are the changes needed?

reduce iops

### How was this patch tested?

passed ut

### Was this patch authored or co-authored using generative AI tooling?

no

### CODE REVIEW

**Comment by wgtmac** [comment]
Thanks for the fix! Could you create a JIRA issue for this?

**Comment by Smith-Cruise** [comment]
> Thanks for the fix! Could you create a JIRA issue for this?

done

**Comment by ffacs** [comment]
+1 LGTM

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM for Apache ORC 2.1.0.

**Comment by dongjoon-hyun** [comment]
Thank you all.

**Comment by dongjoon-hyun** [comment]
BTW, @Smith-Cruise , I officially added you to the Apache ORC contributor group (in ASF JIRA) and assigned ORC-1645 to you. Welcome to the Apache ORC community again.

```
$ git log --oneline --author=chendingchao1
6c24acdbf (HEAD -> main, apache/main, apache/HEAD) ORC-1645: [C++] Evaulate stripe stats before load stripe footer
bbb1f074d MINOR: Fix a typo in `ColumnReader.cc`
```

**Pull request closed without merging**
