### PR TITLE
ORC-998: Sharing compression output buffer among treeWriter: Refactoring within OutStream for portability

### PR DESCRIPTION
**Pull request by mystic-lama**
### What changes were proposed in this pull request?
There's individual instance of OutStream within each TreeWriter created by WriterContext#createStream method. Within OutStream, there are totally 3 buffers:

current: the regular input buffer holding uncompressed, unencrypted bytes.
compress: the output buffer holding compressed bytes
overflow: same as "compress" but only used when the last compression output is larger than remaining capacity of compress buffer.
Potentially the compress and overflow buffer don't have to be allocated individually within each OutStream object, but shared across all of them so to save memory allocation.

This PR is the first step for sharing the compression output buffer, which refactors internal of OutStream and make the relevant object bundled together since they are logically related(and details of dealing with overflow doesn't have to be visible). This refactoring makes it easier to share the compression output buffer as a pass-in arguments in the follow-up PR.

### Why are the changes needed?
For the context of [ORC-997](https://issues.apache.org/jira/browse/ORC-997), this change makes the compression output buffer, as a single entity, easier to be shared and passed in from caller.

### How was this patch tested?
There's no functional changes from this PR so passing all existed unit tests. Also added a new test in TestOutStream to make sure that, the scenario where codec.compress() returns false (meaning the compression output is larger than original input) is also covered in the unit test.

This closes #909

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you for making a PR, but the PR description should be complete by itself instead of referring other PR's content. Since you already add that PR id and authorship in the commit, that's enough. 

Could you revise the PR description?

**Comment by mystic-lama** [comment]
@dongjoon-hyun ACK, shall update the PR. Was not sure, hence kept it it like that

**Comment by mystic-lama** [comment]
PR description updated (copied from original PR)

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

Sorry for being late, @mystic-lama . I finally get enough time to review this, (Thanksgiving Holidays). :)

Merged to main for Apache ORC 2.0.0.

**Comment by dongjoon-hyun** [comment]
Thank you, @mystic-lama . This PR is merged with the following authorship.
- https://github.com/apache/orc/commit/22a06b4e7575f539be970ec9658f5b597ef7c83d
```
Lead-authored-by: mystic-lama <mysticlama000@gmail.com>
Co-authored-by: Lei Sun <autumnust@gmail.com>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>
```

**Comment by mystic-lama** [comment]
> +1, LGTM.
> 
> Sorry for being late, @mystic-lama . I finally get enough time to review this, (Thanksgiving Holidays). :)
> 
> Merged to main for Apache ORC 2.0.0.

@dongjoon-hyun Appreciate all your help :)

**Pull request closed without merging**
