### PR TITLE
ORC-1011: Activate `java17` profile automatically

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to activate `java17` profile automatically on Java17 runtime.

### Why are the changes needed?

This simplifies the development environment.

### How was this patch tested?

Pass CIs with the revised configuration.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @williamhyun

**Review by williamhyun — APPROVED** [review]
+1 LGTM

**Comment by dongjoon-hyun** [comment]
Thank you, @williamhyun and @guiyanakuang .

**Comment by dongjoon-hyun** [comment]
I backported this to branch-1.7 too.

**Pull request merged**
