### PR TITLE
ORC-1102: Upgrade ZSTD to 1.5.2

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to upgrade ZSTD to 1.5.2.

### Why are the changes needed?

This will bring the latest bug fixes and improvements.
- https://github.com/facebook/zstd/releases/tag/v1.5.2

### How was this patch tested?

Pass the CIs.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @williamhyun and @guiyanakuang

**Review by williamhyun — APPROVED** [review]
+1 LGTM

**Comment by dongjoon-hyun** [comment]
Thank you for your review and merging, @williamhyun .

**Comment by dongjoon-hyun** [comment]
I cherry-picked this to branch-1.7 too.

**Pull request merged**
