### PR TITLE
Orc-100 fixing maven compile site errors and ensuring build failure in case of findbug errors.

### PR DESCRIPTION
**Pull request by tarunk2**
#### Changes include:
- Fixing `mvn clean compile site` errors. `tools` module should have findbugs `exclude.xml`.
- Maven build should fail if there are any findbug errors.

#### Testing:
- [x] maven build passes locally and there no findbug errors.

### CODE REVIEW

**Comment by omalley** [comment]
Thanks. We also need to add the plugin to the build sections of the children poms and unfortunately fix a few items.  Does this look ok? https://github.com/omalley/orc/commits/orc-100

**Comment by tarunk2** [comment]
Thanks, looks good. Alternatively, we can move `findbugs-maven-plugin` outside of `pluginManagement` and it won't need explicit plugin in children poms.

**Comment by tarunk2** [comment]
@omalley should i pull your commit in this PR or you will merge changes from your fork?

**Comment by omalley** [comment]
I can do the merge, thanks though!

**Comment by omalley** [comment]
I did also move the plugin to the build in the root pom.

**Pull request closed without merging**
