### PR TITLE
ORC-740: Add curl in debian and ubuntu Docker files

### PR DESCRIPTION
**Pull request by williamhyun**
### What changes were proposed in this pull request?

This PR aims to add curl in debian and ubuntu Docker files.

### Why are the changes needed?

Since we use mvnw, we need curl or wget. 

### How was this patch tested?

Pass the CIs.

### CODE REVIEW

**Comment by pgaref** [comment]
+1 pending tests

**Comment by pgaref** [comment]
> +1 pending tests

Even though CI tests are using plain ubuntu 20 and not our Dockerfiles -- maybe something to support in the future (at least pre-release)

**Comment by dongjoon-hyun** [comment]
Oh,  got it. Thank you, @williamhyun and @pgaref .
Merged to master/1.6.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Yes, pending CI although this should be tested manually.

**Comment by dongjoon-hyun** [comment]
It seems that `Travis CI` has some issues. The master branch is not triggered for 8 hours and the situation is similar (6 hour) here.

**Comment by dongjoon-hyun** [comment]
I'll merge this to master/1.6.

**Pull request closed without merging**
