### PR TITLE
ORC-803: MemoryManagerImpl Simplify removeWriter

### PR DESCRIPTION
**Pull request by belugabehr**
### What changes were proposed in this pull request?
Within the class MemoryManagerImpl, removing a writer can be simplified down to a single Map interaction.

### Why are the changes needed?
Change reduces code size and allows the Map to be scanned only one time instead of twice (in some scenarios).

### How was this patch tested?
Existing unit tests

### CODE REVIEW

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Thank you for making a PR, @belugabehr .
Could you fill the PR description? It will be a Git commit message body.

**Comment by dongjoon-hyun** [comment]
Gentle ping, @belugabehr .

**Comment by belugabehr** [comment]
@dongjoon-hyun Thanks for being on top of things. Let me know if the information provided will suffice.  Thanks.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @belugabehr .
Merged to main for Apache ORC 1.7.0.

**Pull request merged**
