### PR TITLE
ORC-557: Fix the issue when orc-tool opens the huge file over 4GB

### PR DESCRIPTION
**Pull request by yuokada**
I have confirmed this patch works on my laptop.
But I don't have enough confidence to this patch.

### CODE REVIEW

**Comment by omalley** [comment]
Thank you for your problem report and fix. I think we need to generalize the fix a little bit to walk through the input buffers for uncompressed streams. I'll upload a revised fix and the corresponding test.

**Comment by omalley** [comment]
Sorry, I referenced this PR by mistake on the fix for ORC-552. I know this is still open.

**Comment by omalley** [comment]
@yuokada can you please try out my fix on #439?

**Comment by yuokada** [comment]
@omalley I've tried your PR. It looks good to me.

**Comment by omalley** [comment]
Ok, this was fixed by 9891eae .

**Pull request closed without merging**
