### PR TITLE
ORC-687. Upgrade to JUnit5

### PR DESCRIPTION
**Pull request by williamhyun**
### What changes were proposed in this pull request?
This PR aims to upgrade JUnit from JUnit4 to JUnit5.

### Why are the changes needed?
This is a stepping stone for migrating to JUnit5. 

### How was this patch tested?
Pass the CIs.

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @williamhyun .

**Comment by dongjoon-hyun** [comment]
cc @pgaref

**Review by pgaref — APPROVED** [review]
LGTM as well !

**Comment by pgaref** [comment]
Merged to master. Thanks @williamhyun for the PR and @dongjoon-hyun for the review !

**Comment by dongjoon-hyun** [comment]
Thank you. Congratulation for your first merging, @pgaref ! 😄

**Pull request merged**
