### PR TITLE
ORC-856: Fix exception description in findSubtype

### PR DESCRIPTION
**Pull request by guiyanakuang**
### What changes were proposed in this pull request?

Fix the exception description in the findSubtype method

### Why are the changes needed?

Avoid misleading exception output

### How was this patch tested?

N/A

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
Thank you for making a PR, @guiyanakuang .

**Comment by dongjoon-hyun** [comment]
Pending CIs.

**Comment by dongjoon-hyun** [comment]
Merged to main for Apache ORC 1.8.0.

**Comment by dongjoon-hyun** [comment]
Welcome to the Apache ORC community. What is your JIRA ID, @guiyanakuang ?

**Comment by guiyanakuang** [comment]
JIRA ID: Guiyankuang，Very happy to contribute code

**Comment by dongjoon-hyun** [comment]
Thank you, @guiyanakuang . I added you to the Apache ORC contributor group and assigned ORC-856 to you.

**Pull request merged**
