### PR TITLE
ORC-673: PPD LTE Point equality comparison is wrong when RG MIN==MAX

### PR DESCRIPTION
**Pull request by pgaref**
### What changes were proposed in this pull request?
FIx PPD Less than Equals comparison for min==max corner case

### Why are the changes needed?
Better PPD evaluation

### How was this patch tested?
Extra JUnit test

### CODE REVIEW

**Comment by pgaref** [comment]
Hey @omalley @dongjoon-hyun  @jcamachor can you please take a look?

**Review by dongjoon-hyun — COMMENTED** [review]
Hi, @pgaref .
Could you update the affected version on ORC-673 ?

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by pgaref** [comment]
Hey @dongjoon-hyun  thanks for the fast review! 
Since this patch is fixing PPD behaviour for LTE comparisons I believe we should also backport to 1.5 and 1.6

**Comment by dongjoon-hyun** [comment]
Please make a backporting PR, @pgaref .
BTW, it would be great if you adds the required versions into `Affected Versions` next time.
I didn't backport this PR because the affected version field is empty.

**Comment by pgaref** [comment]
Hey @dongjoon-hyun  -- you are right, will make sure the affected versions are properly set next time :)
Also 1.5 needed a bit of tweaking so I just opened #551 and #552 for the backports

**Pull request merged**
