### PR TITLE
ORC-1413. Fix for ORC row level filter issue with ACID table

### PR DESCRIPTION
**Pull request by zratkai**
ORC-1413 fix for ORC row level filter issue with ACID table

### What changes were proposed in this pull request? 
This PR fixes ORC row level filter with ACID table issue. 

### Why are the changes needed? 
Without this Hive can not work with ORC 1.8.3. and ACID table and row level filter enabled. 

### How was this patch tested? 
Unit test added.

### CODE REVIEW

**Comment by zratkai** [comment]
@pavibhai cherry-picked .

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @zratkai .
Merged to branch-1.8 for Apache ORC 1.8.4.

**Comment by dongjoon-hyun** [comment]
Apache ORC 1.8.4 SNAPSHOT are published. Could you test it with Apache Hive, @zratkai ?
Please let us know if you need more patches.

**Comment by zratkai** [comment]
@dongjoon-hyun I test it and let you know if I need anything. Thanks!

**Comment by dongjoon-hyun** [comment]
Thank you!

**Comment by pavibhai** [comment]
> @dongjoon-hyun I test it and let you know if I need anything. Thanks!

@zratkai was curious to see if you have an update on this. Thank you.

**Comment by zratkai** [comment]
> > @dongjoon-hyun I test it and let you know if I need anything. Thanks!
> 
> @zratkai was curious to see if you have an update on this. Thank you.

@dongjoon-hyun unfortunately I didn't have time since, I had other task to solve. I am on holiday now, hopefully after I will have time to test.

**Pull request closed without merging**
