### PR TITLE
ORC-819: Add GitHub labeler

### PR DESCRIPTION
**Pull request by williamhyun**
### What changes were proposed in this pull request?
This PR aims to add GitHub labeler. 

### Why are the changes needed?
This assists the reviewer to categorize and find the PRs easily.  

### How was this patch tested?
N/A.

### CODE REVIEW

**Comment by williamhyun** [comment]
cc: @pgaref @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Oh, thank you for pinging me, @williamhyun . This is a nice feature!

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Let's merge this and test it directly.

**Comment by dongjoon-hyun** [comment]
I merged this for you. :)

**Comment by williamhyun** [comment]
Thank you for the swift review and merge!

**Pull request merged**
