### PR TITLE
ORC-960: [C++] Support creating SearchArguments using column ids

### PR DESCRIPTION
**Pull request by stiga-huang**
### What changes were proposed in this pull request?

Currently in the C++ reader, SearchArgumentBuilder only provides interfaces for creating SearchArguments using field column names. Column names can be ambiguous if there are nested struct columns using the same names. Array item column or map key/value columns even don't have names.

This patch addes corresponding interfaces to create SearchArguments using column ids. Refactors some codes using templates to avoid duplicated codes.

### Why are the changes needed?

As described above and in the JIRA description, we need creating SearchArguments using column ids.

### How was this patch tested?

Added end-to-end tests in c++/test/TestPredicatePushdown.cc.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you for making a PR, @stiga-huang .

**Comment by dongjoon-hyun** [comment]
cc @wgtmac

**Review by wgtmac — APPROVED** [review]
Overall LGTM. It is possible that user mixes use of fieldName and columnId in a single SearchArgumentBuilder which is weird but valid.

**Comment by dongjoon-hyun** [comment]
Thank you, @wgtmac . 
According to the affected version of ORC-960, @stiga-huang seems to create ORC-960 for Apache ORC 1.7.0.
Although Apache ORC 1.7 has been in the feature freeze status, do you think we need to land this in branch-1.7?

**Comment by stiga-huang** [comment]
Impala will wait for this feature. It'd be good if the coming ORC 1.7.0 release can have it.

**Comment by wgtmac** [comment]
> Thank you, @wgtmac .
> According to the affected version of [ORC-960](https://issues.apache.org/jira/browse/ORC-960), @stiga-huang seems to create [ORC-960](https://issues.apache.org/jira/browse/ORC-960) for Apache ORC 1.7.0.
> Although Apache ORC 1.7 has been in the feature freeze status, do you think we need to land this in branch-1.7?

This change is limited to C++ only. I am OK if landing it into branch-1.7 will not delay the release process.

**Comment by dongjoon-hyun** [comment]
Got it, @stiga-huang and @wgtmac .

**Comment by dongjoon-hyun** [comment]
Merged to main/branch-1.7 for Apache ORC 1.7.

**Comment by dongjoon-hyun** [comment]
BTW, the current release blocker is ORC-811 (LazyIO of non-filter columns benchmark) and Apache Iceberg Integration Testing.
- https://github.com/dongjoon-hyun/iceberg/pull/7

**Pull request merged**
