### PR TITLE
MINOR: Add Yuanping Wu to committers page

### PR DESCRIPTION
**Pull request by ffacs**
### What changes were proposed in this pull request?

This PR aims to add `Yuanping Wu` to the committers page.

### Why are the changes needed?

To keep the list of committers for the ORC website up to date.

### How was this patch tested?

N/A

### Was this patch authored or co-authored using generative AI tooling?
No

### CODE REVIEW

**Comment by ffacs** [comment]
cc @dongjoon-hyun @wgtmac

**Review by cxzl25 — APPROVED** [review]
Congrats!

**Review by wgtmac — APPROVED** [review]

**Review by wgtmac — CHANGES_REQUESTED** [review]
Could you please try to sort names by Apache id?

**Comment by ffacs** [comment]
> Could you please try to sort names by Apache id?

Done

**Review by wgtmac — APPROVED** [review]
Thanks! Please merge this when you are ready.

**Pull request closed without merging**
