### PR TITLE
ORC-823: Upgrade maven-assembly-plugin to 3.3.0

### PR DESCRIPTION
**Pull request by williamhyun**
### What changes were proposed in this pull request?
This PR aims to upgrade maven-assembly-plugin to 3.3.0.

### Why are the changes needed?
This is required to build with Java 17.

### How was this patch tested?
Pass the CIs.

### CODE REVIEW

**Comment by williamhyun** [comment]
cc: @pgaref @dongjoon-hyun

**Comment by williamhyun** [comment]
I made a PR to test Java 17 independently, it is expected to fail. 
- https://github.com/apache/orc/pull/728

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @williamhyun .
I saw your WIP PR. Is this the last one?

**Comment by dongjoon-hyun** [comment]
Merged to master.

**Comment by dongjoon-hyun** [comment]
To deliver this for Apache ORC 1.7.0, we need to backport this to branch-1.7 specifically. I backported it.

**Pull request merged**
