### PR TITLE
Add Pavan Lanka as committer on site

### PR DESCRIPTION
**Pull request by pavibhai**
### What changes were proposed in this pull request?
Added Pavan Lanka as a committer to the site

### Why are the changes needed?
To update the list of committers

### How was this patch tested?
Manual review by bringing up the site locally

### CODE REVIEW

**Review by omalley — APPROVED** [review]
+1 LGTM

**Comment by guiyanakuang** [comment]
+1 LGTM, @pavibhai, feel free to merge this PR.

**Comment by pavibhai** [comment]
Thanks @omalley and @guiyanakuang I was able to merge the PR

**Review by dongjoon-hyun — COMMENTED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
BTW, @pavibhai . Could you publish this update to the [Apache ORC website](https://orc.apache.org/develop/committers/)? Please follow [the instruction](https://github.com/apache/orc/blob/main/site/README.md).

**Comment by pavibhai** [comment]
> Could you publish this update to the [Apache ORC website](https://orc.apache.org/develop/committers/)?

Sure @dongjoon-hyun will do this.

**Comment by pavibhai** [comment]
@dongjoon-hyun I was able to publish the change to the ORC site.

**Comment by dongjoon-hyun** [comment]
Thank you, @pavibhai .

**Comment by dongjoon-hyun** [comment]
I'll add a news article about your committership and announce in LinkedIn.

**Comment by dongjoon-hyun** [comment]
Here is a news page for you.
- https://orc.apache.org/news/2022/06/05/add-pavan/

**Comment by pavibhai** [comment]
>     * https://orc.apache.org/news/2022/06/05/add-pavan/

Thanks @dongjoon-hyun

**Pull request merged**
