### PR TITLE
ORC-841: Remove Superfluous Array Fill in StringHashTableDictionary

### PR DESCRIPTION
**Pull request by belugabehr**
### What changes were proposed in this pull request?
Remove Superfluous Array Fill in StringHashTableDictionary. Java GC will take care of this.

### Why are the changes needed?
Less code. Performance.

### How was this patch tested?
No changes to functionality. Uses existing unit tests.

### CODE REVIEW

**Review by williamhyun — APPROVED** [review]
+1 LGTM

**Comment by williamhyun** [comment]
cc: @dongjoon-hyun and @pgaref

**Comment by dongjoon-hyun** [comment]
Thank you, @belugabehr and @williamhyun .

**Comment by pgaref** [comment]
Late LGTM ! Thanks all !

**Pull request closed without merging**
