### PR TITLE
ORC-1123: Add `estimationMemory` method for writer

### PR DESCRIPTION
**Pull request by guiyanakuang**
### What changes were proposed in this pull request?

Add `estimationMemory` method for writer. It exposes the internal treeWriter to estimate the memory used for the buffer.

### Why are the changes needed?

This method help the write engine to better control the refresh policy of the ORC.

The source of this issue comes from Iceberg's discussion.
https://lists.apache.org/thread/g6yo7m46mr86ov1vkm9wnmshgw7hcl6b

### How was this patch tested?

Pass the CIs

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @guiyanakuang .
I also read the background and get pings.
Merged to main/1.7 for Apache ORC 1.7.4.

**Comment by dongjoon-hyun** [comment]
Also, cc @williamhyun since he is the release manager for Apache ORC 1.7.4.

**Comment by pgaref** [comment]
Seems like we might be overestimating memory usage when taking into account unused buffers -- would probably make sense documenting/testing these estimates.

**Comment by dongjoon-hyun** [comment]
+1 for doing that separately in a new ORC JIRA.

**Comment by hililiwei** [comment]
> Seems like we might be overestimating memory usage when taking into account unused buffers -- would probably make sense documenting/testing these estimates.

In my tests, it did overestimate a bit.

**Pull request merged**
