### PR TITLE
ORC-1819: Publish snapshot website through GitHub Pages

### PR DESCRIPTION
**Pull request by williamhyun**
### What changes were proposed in this pull request?
This PR aims to publish the Apache ORC snapshot website through GitHub Pages.

### Why are the changes needed?
To provide users with the most recent updates on the website in between releases.

### How was this patch tested?
Manually.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Comment by williamhyun** [comment]
cc: @dongjoon-hyun, @wgtmac

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you for making this, @williamhyun . This is a nice Christmas present to the Apache ORC community. 😄

**Comment by dongjoon-hyun** [comment]
Let's merge this and see the result.

**Comment by dongjoon-hyun** [comment]
Merged to main.

**Comment by dongjoon-hyun** [comment]
I verified that it's live now. It looks good to me although there are some absolute news link issues. Thank you.
- https://apache.github.io/orc/

**Comment by williamhyun** [comment]
Thank you! @dongjoon-hyun 

Happy Holidays :)

**Comment by wgtmac** [comment]
Wow, it's great to have this! Thanks @williamhyun @dongjoon-hyun!

**Comment by williamhyun** [comment]
Thank you Gang and happy holidays!

**Pull request closed without merging**
