### PR TITLE
ORC-1302: Upgrade Github workflow to use `Visual Studio 16 2019` on Windows

### PR DESCRIPTION
**Pull request by wgtmac**
### What changes were proposed in this pull request?
Upgrade Github workflow to build on Windows to use higher version of Visual Studio. To be specific, the workflow uses Visual Studio 16 2019 instead of Visual Studio 14 2015.

### Why are the changes needed?
This is the prerequisite for the C++17 movement across the C++ code base.

### How was this patch tested?
Pass all the CI checks.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you for working on this. Is it better if we use [windows-2022](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md)  GitHub Action runner instead of `windows-2019`?

```
  windows:
    name: "Build on Windows"
    runs-on: windows-2019
```

**Comment by wgtmac** [comment]
> #1298 is merged. Could you rebase this PR?

Done.

I have tried windows-2022 but it ended up with error related to finding Visual Studio 2019.

**Comment by wgtmac** [comment]
cc @stiga-huang

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @wgtmac . 
Yes, `Visual Studio 16 2019` is good enough for now.
We can revisit the underlying OS issue later.

**Comment by dongjoon-hyun** [comment]
Unfortunately, this seems to require #1298. After 750e615091e399569e1f8a1c1491a5d2f343539c, Windows GitHub Action job of `branch-1.8` starts to fail at Google Test compilation.
- https://github.com/apache/orc/actions/runs/3571364150/jobs/6003165821
```
CMake Error at D:/a/orc/orc/build/googletest_ep-prefix/src/googletest_ep-stamp/googletest_ep-build-Debug.cmake:49 (message):
    Command failed: 1
     'C:/Program Files/CMake/bin/cmake.exe' '--build' '.' '--config' 'Debug'
```

**Comment by wgtmac** [comment]
> Unfortunately, this seems to require #1298. After [750e615](https://github.com/apache/orc/commit/750e615091e399569e1f8a1c1491a5d2f343539c), Windows GitHub Action job of `branch-1.8` starts to fail at Google Test compilation.
> 
> * https://github.com/apache/orc/actions/runs/3571364150/jobs/6003165821
> 
> ```
> CMake Error at D:/a/orc/orc/build/googletest_ep-prefix/src/googletest_ep-stamp/googletest_ep-build-Debug.cmake:49 (message):
>     Command failed: 1
>      'C:/Program Files/CMake/bin/cmake.exe' '--build' '.' '--config' 'Debug'
> ```

Does it mean that the it applies github workflow config from the main branch even for commits to branch-1.8?

**Comment by dongjoon-hyun** [comment]
No~ I backported this to `branch-1.8` too at that time.

https://github.com/apache/orc/commit/7f99a7aa10695855a44cfb0b78f21d61a59c20c6

Let me revert this first from branch-1.8 to prepare Apache ORC 1.8.1 release. We can keep this for Apache ORC 1.9.0 and maybe 1.8.2 later.

**Comment by dongjoon-hyun** [comment]
This is reverted from branch-1.8 via https://github.com/apache/orc/commit/36c54888b6e0cab02ecdc6960ee6b189d921ee05

**Comment by dongjoon-hyun** [comment]
`branch-1.8` GitHub Action `Windows` job is recovered.

Screenshot 2022-11-28 at 10 56 07 PM

**Pull request closed without merging**
