### PR TITLE
ORC-813: Upgrade ZSTD to 1.5.0

### PR DESCRIPTION
**Pull request by dchristle**
### What changes were proposed in this pull request?
This PR aims to upgrade ZSTD from 1.4.5 to 1.5.0.

### Why are the changes needed?
This will bring in the latest performance improvements and bugfixes:
- https://github.com/facebook/zstd/releases/tag/v1.5.0
- https://github.com/facebook/zstd/releases/tag/v1.4.9
- https://github.com/facebook/zstd/releases/tag/v1.4.8
- https://github.com/facebook/zstd/releases/tag/v1.4.7

### How was this patch tested?
Pass the CIs.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
@dchristle . 
This PR updates Apache ORC C++ reader and writer while Apache ORC Java Reader and Writer is still behind because of the following.
```
      <dependency>
        <groupId>io.airlift</groupId>
        <artifactId>aircompressor</artifactId>
        <version>0.16</version>
      </dependency>
```

**Comment by dongjoon-hyun** [comment]
cc @wgtmac

**Comment by wgtmac** [comment]
> Thank you for making a PR, @dchristle .
> 
> BTW, this PR updates Apache ORC C++ reader and writer while Apache ORC Java Reader and Writer is still behind because of the following. We need to verify that native ZSTD 1.5.0 works with old air compressor library.
> 
> ```
>       <dependency>
>         <groupId>io.airlift</groupId>
>         <artifactId>aircompressor</artifactId>
>         <version>0.16</version>
>       </dependency>
> ```

I have checked the release note and haven't found any format incompatible issue.

**Comment by dongjoon-hyun** [comment]
Thank you, @wgtmac . I'll leave this for you. Feel free to merge this for Apache ORC 1.7.0.

**Review by wgtmac — APPROVED** [review]
+1 LGTM. Thanks @dchristle for contribution and @dongjoon-hyun for review!

**Comment by dongjoon-hyun** [comment]
@dchristle . I added you to the Apache ORC contributor group and assigned ORC-813 to you. Thank you again.

**Pull request merged**
