### PR TITLE
ORC-1530: Rename variables in `RecordReaderUtils.ChunkReader#create`

### PR DESCRIPTION
**Pull request by yebukong**
### What changes were proposed in this pull request?

rename variables in RecordReaderUtils.ChunkReader#create

### Why are the changes needed?

for easy reading 

see [PR 1662](https://github.com/apache/orc/pull/1662#discussion_r1404534922)

### CODE REVIEW

**Comment by mystic-lama** [comment]
@yebukong Better to have a different JIRA for renaming to avoid confusion. ORC-1528 talks about the overflow problem and may cause confusion later. We can reference the discussion on the PR too. However, please wait for confirmation from community on this, as this just how I would do it 😄

**Review by mystic-lama — APPROVED** [review]
+1 LGTM

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by yebukong** [comment]
Thank you @Dongjoon Hyun, for reporting [ORC-1530](https://issues.apache.org/jira/browse/ORC-1530) . 

The next step for me is to locally merge the "renaming PR" into the "main PR" and then proceed to complete the main PR, correct?

**Comment by dongjoon-hyun** [comment]
Sorry but it's not, @yebukong .

As you see on the JIRA issue ORC-1530, this PR is a kind of improvement or a simple task which is only worthy for `main` branch for Apache ORC 2.0.0.

Screenshot 2023-11-26 at 5 18 24 PM

However, your original PR is categorized a bug fix for branch-1.8 which means we need to land this to `main/branch-1.9/branch-1.8`.

- #1662

Since `branch-1.9` and `branch-1.8` cannot have ORC-1530 (this renaming PR), I prefer to proceed #1662 first based on the original code which is identical to `branch-1.9` and `branch-1.8`.

**Comment by yebukong** [comment]
Thank you for the response @dongjoon-hyun  . I understand.

I will first revert the ["rename variables" commit](https://github.com/apache/orc/pull/1662/commits/88aecc6b4460253a0402b706d45451abf35b1494) in the #1662 (the original fix PR) and then proceed to complete #1662.

**Comment by dongjoon-hyun** [comment]
Since I merged the following PR, could you rebase this PR once more, @yebukong ?
- #1662

**Comment by yebukong** [comment]
I have rebased onto the["apache/orc:main"](https://github.com/apache/orc/commits/main) commit [fbd1515](https://github.com/apache/orc/commit/fbd1515f395e40be4e316f8cdc762a1ec821763b) and force-pushed. @dongjoon-hyun PTAL.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CIs). Thank you for updating, @yebukong .

**Pull request closed without merging**
