### PR TITLE
ORC-598: Unable to read ORC file with struct and array.length > 1024

### PR DESCRIPTION
**Pull request by kasakrisz**
See repro in jira details.
@prasanthj Please review.

### CODE REVIEW

**Comment by prasanthj** [comment]
@kasakrisz can we add a unit test for this?

**Comment by kasakrisz** [comment]
@prasanthj 
Added unit test for all conversions.

**Comment by prasanthj** [comment]
+1

**Comment by dongjoon-hyun** [comment]
Hi, @prasanthj and @kasakrisz .
According to the JIRA affected versions and https://github.com/apache/orc/pull/568#issuecomment-723187458 , I'll backport this to release branches.

**Pull request merged**
