### PR TITLE
ORC-726: Support Map type in `orc-tools convert`

### PR DESCRIPTION
**Pull request by guiyanakuang**
### What changes were proposed in this pull request?

Implement MapType to support multiple ORC files for convert.

### Why are the changes needed?

Feature Improvement.

### How was this patch tested?

Added testMapMerges unit test.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you for working on this, @guiyanakuang .

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you so much. I verified manually.

```
$ java -jar java/tools/target/orc-tools-1.8.0-SNAPSHOT-uber.jar convert examples/orc-file-11-format.orc examples/orc-file-11-format.orc
log4j:WARN No appenders could be found for logger (org.apache.hadoop.util.Shell).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Merging schema from examples/orc-file-11-format.orc
Merging schema from examples/orc-file-11-format.orc
Processing examples/orc-file-11-format.orc
Processing examples/orc-file-11-format.orc
```

```
$ orc-tools meta output.orc
log4j:WARN No appenders could be found for logger (org.apache.hadoop.util.Shell).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Processing data file output.orc [length: 7446]
Structure for output.orc
File Version: 0.12 with ORC_14
Rows: 15000
Compression: ZLIB
Compression size: 131072
Calendar: Julian/Gregorian
Type: struct<boolean1:boolean,byte1:tinyint,bytes1:binary,decimal1:decimal(38,10),double1:double,float1:float,int1:int,list:array<struct<int1:int,string1:string>>,long1:bigint,map:map<string,struct<int1:int,string1:string>>,middle:struct<list:array<struct<int1:int,string1:string>>>,short1:smallint,string1:string,ts:timestamp>
...
```

**Comment by dongjoon-hyun** [comment]
Merged to main. (BTW, I missed to revise the commit title with ORC ID).

**Comment by dongjoon-hyun** [comment]
I backported this to branch-1.7 for Apache ORC 1.7, too.

**Comment by guiyanakuang** [comment]
Thanks to @dongjoon-hyun for a quick review and manual verification.

**Pull request merged**
