### PR TITLE
ORC-1506: Replacing deprecated valueOf() with recommended forNumber()

### PR DESCRIPTION
**Pull request by mystic-lama**
### What changes were proposed in this pull request?
The PR aims at replacing deprecated valueOf() with recommended forNumber().
valueOf() has been deprecated for a while and shall be removed in future versions. We are only removing it from the code we have written, it still exists in auto-generated code. Autogenerate code shall be compliant with version upgrade in future.

Couldn't find the exact PR for the change, however the reason seems to be performance related from search about the change

### Why are the changes needed?
The change helps protect against the removal of deprecated API in future releases.

### How was this patch tested?
No new tests were added, current tests pass

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Is this PR fixing all instances of `ProtoBuffer valueOf usage?

**Comment by mystic-lama** [comment]
@dongjoon-hyun Let me check once again. I found it as I was reading code and the inspection didn't yield anything else. I shall validate once again and update code if needed.

**Comment by dongjoon-hyun** [comment]
Thank you, @mystic-lama .

**Comment by mystic-lama** [comment]
@dongjoon-hyun I check the code and didn't find any other usage. Auto-generate code does use the valueOf(), however not planing on changing it here. Not sure what all it may break, if someone is using it outside of this repo. The valueOf() is internally calling forNumber().

```java
/**
  * @param value The numeric wire value of the corresponding enum entry.
  * @return The enum associated with the given numeric wire value.
  * @deprecated Use {@link #forNumber(int)} instead.
  */
  @java.lang.Deprecated
  public static EncryptionAlgorithm valueOf(int value) {
    return forNumber(value);
  }
```

Let me know if I need to investigate more.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Pull request closed without merging**
