### PR TITLE
ORC-921: Add an encrypted example file

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to add an encrypted example file to the `example` directory.

### Why are the changes needed?

`example` directory is a good place to show Apache ORC feature.

### How was this patch tested?

This is an example file which can be read by the following.

**From Java Tools**
```
$ cd java
$ mvn package -DskipTests
$ java -jar tools/target/*-uber.jar data ../examples/encrypted/*.orc 2> /dev/null
{"ssn":null,"email":"841626795E7D351555B835A002E3BF10669DE9B81C95A3D59E10865AC37EA7C3","name":"Dongjoon Hyun"}
________________________________________________________________________________________________________________________

{"ssn":null,"email":"B948E77D79105EAA53E54502CB39DA20C6A86263FA301D5B7EDBACC66D15B642","name":"William Hyun"}
________________________________________________________________________________________________________________________
```

**From Spark 3.2 + Hadoop KMS with the provided `kms.keystore` file**
```
export HADOOP_KEYSTORE_PASSWORD=ORC_KEY
bin/hadoop --daemon start kms
```
```
scala> spark.read.option("orc.key.provider", "hadoop").option("hadoop.security.key.provider.path", "kms://http@localhost:9600/kms").option("orc.encrypt", "pii:ssn,email").orc("sample.orc").show
+---------+-------------------+-------------+
|      ssn|              email|         name|
+---------+-------------------+-------------+
|123456789|dongjoon@apache.org|Dongjoon Hyun|
+---------+-------------------+-------------+
```

### CODE REVIEW

**Review by williamhyun — CHANGES_REQUESTED** [review]
I cannot decrypt the `sample.orc` with the given key.
Could you check again please?

**Review by williamhyun — APPROVED** [review]
It seems to work with that change. 

```
scala> spark.read.option("orc.key.provider", "hadoop").option("hadoop.security.key.provider.path", "kms://http@localhost:9600/kms").option("orc.encrypt", "pii:ssn,email").orc("/Users/william/RC/orc/examples/encrypted/sample*.orc").show
+---------+-------------------+-------------+
|      ssn|              email|         name|
+---------+-------------------+-------------+
|123456789|dongjoon@apache.org|Dongjoon Hyun|
|987654321| william@apache.org| William Hyun|
+---------+-------------------+-------------+
```

**Comment by dongjoon-hyun** [comment]
Thank you so much, @williamhyun !

**Comment by dongjoon-hyun** [comment]
I updated the PR description, too. :)

**Comment by dongjoon-hyun** [comment]
Merged to main/branch-1.7.

**Comment by dongjoon-hyun** [comment]
I backported this to branch-1.6 too.

**Pull request merged**
