### PR TITLE
ORC-811 Benchmarks and documentation for ORC-742 and ORC-743

### PR DESCRIPTION
**Pull request by pavibhai**
### What changes were proposed in this pull request?
Includes Benchmark tests and Documentation for ORC-742 and ORC-743

### Why are the changes needed?
Benchmarks show the benefits of adding LazyIO during reads and the documentation explains the design of the same.

### How was this patch tested?
There is no new functionality added here so the regression tests were run and the benchmark tests were completed to verify the improvements.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you, @pavibhai .

**Review by dongjoon-hyun — COMMENTED** [review]
@pavibhai . Can we move some of the tests from `bench` module to normal modules? It's a little weird for `bench` module to have a test coverage because this is not executed by default.

**Comment by pavibhai** [comment]
> @pavibhai . Can we move some of the tests from `bench` module to normal modules? It's a little weird for `bench` module to have a test coverage because this is not executed by default.

@dongjoon-hyun These tests have been added specifically to verify the benchmark code with unit tests. The other modules already have this test coverage, so these tests should belong here.

**Comment by dongjoon-hyun** [comment]
Then, could you spin off them as a new test PR, @pavibhai ?

**Comment by pavibhai** [comment]
> Then, could you spin off them as a new test PR, @pavibhai ?

Sorry I am confused. These are tests I am adding for the benchmarks that are being added as part of this PR. Why do you want to separate the tests into another PR?

**Comment by omalley** [comment]
I think it is better practice to include the tests with the PR that adds the code. Since the tests are for the benchmark code, it makes sense to include them here.

**Comment by dongjoon-hyun** [comment]
Got it if you think so, @omalley .

**Comment by pavibhai** [comment]
@omalley @pgaref the benchmark and documentation PR is ready for review. Please take a look at it when you get a chance.

**Pull request merged**
