### PR TITLE
ORC-1244: Upgrade `byte-buddy` to 1.12.13 in branch-1.7

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to upgrade a test dependency, `byte-buddy`, in branch-1.7 to 1.12.13.

### Why are the changes needed?

To sync with branch-1.8 and main.

### How was this patch tested?

Pass the CIs.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this, @williamhyun ?

**Comment by dongjoon-hyun** [comment]
Gentle ping, @williamhyun .

**Review by williamhyun — APPROVED** [review]
+1 LGTM

**Comment by dongjoon-hyun** [comment]
Thank you, @williamhyun .

**Pull request merged**
