### PR TITLE
ORC-748: Add separate writer implementation for Trino

### PR DESCRIPTION
**Pull request by findepi**
### What changes were proposed in this pull request?

This PR aims to add a writer version for Trino.

### Why are the changes needed?

Trino writer is different from Presto writer.

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by findepi** [comment]
cc @dain

**Comment by pgaref** [comment]
Hey @findepi thanks for the PR! I lack context here so:
Can you please elaborate why this change is needed? Are you using a custom ORCWritter implementation for Trino? If yes can you please share details and add a link as part of the comment please?

In general we also map PRs to Jira tickets so I would encourage you to open one describing the details behind this change.

Cheers,
Panagiotis

**Comment by findepi** [comment]
@pgaref thank you for your review!
I filed https://issues.apache.org/jira/browse/ORC-748 and added rationale there.

**Review by dongjoon-hyun — COMMENTED** [review]
What do you think about this, @omalley ?

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @findepi and @pgaref .
Merged to master for Apache ORC 1.7.0.

**Comment by findepi** [comment]
Thanks @dongjoon-hyun for the merge. Can you please close the jira issue as well?

**Comment by dongjoon-hyun** [comment]
Oh, sure!

**Comment by dongjoon-hyun** [comment]
You are added to the Apache ORC contributor group and ORC-748 is assigned to you, @findepi .
Welcome to the Apache ORC community. Thank you!

**Pull request merged**
