### PR TITLE
ORC-821: Use mvnw instead of mvn

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR uses `mvnw` instead of `mvn` in our build system and documentation.

### Why are the changes needed?

For consistency.

### How was this patch tested?

Pass the CIs.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @pgaref . This is a PR based on the your review comment when I introduced `mvnw` at the first time. Could you review this?

Also, cc @williamhyun

**Comment by dongjoon-hyun** [comment]
Could you review this too, @williamhyun ? :)

**Comment by dongjoon-hyun** [comment]
The first commit passed and the second commit is only about `md` file. So, the result is the same.

**Comment by dongjoon-hyun** [comment]
Now it passed.

**Review by williamhyun — APPROVED** [review]
+1 LGTM

**Comment by dongjoon-hyun** [comment]
Thank you so much! Merged to master/branch-1.6.

**Pull request merged**
