### PR TITLE
ORC-1706: [C++] Fix build break w/ BUILD_CPP_ENABLE_METRICS=ON

### PR DESCRIPTION
**Pull request by ffacs**
### What changes were proposed in this pull request?
1. Fix build break w/ BUILD_CPP_ENABLE_METRICS=ON
2. Add -DBUILD_CPP_ENABLE_METRICS=ON on format check actions.
3. Fix a typo on README file name.

### Why are the changes needed?
C++ build breaks when the option BUILD_CPP_ENABLE_METRICS is switched on.

### How was this patch tested?
UT passed.

### Was this patch authored or co-authored using generative AI tooling?
NO

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
(Pending CIs)

**Review by wgtmac — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Feel free to merge, @wgtmac ~ :)

**Comment by ffacs** [comment]
> Got it. Are these all leftovers due to the recent variable renaming change?

Yes

**Comment by wgtmac** [comment]
I just merged it. Thanks @ffacs and @dongjoon-hyun!

**Pull request closed without merging**
