### PR TITLE
ORC-1608: Upgrade Hadoop to 3.4.0

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to upgrade Apache Hadoop dependency to 3.4.0.

### Why are the changes needed?

To use the latest Hadoop features.
- https://hadoop.apache.org/docs/r3.4.0

### How was this patch tested?

Pass the CIs.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
This is WIP because this PR is testing Apache Hadoop 3.4.0 RC1.
- https://lists.apache.org/thread/gzx1tr0x57oh7q88fh8hd0917jl00mf6

**Comment by dongjoon-hyun** [comment]
It seems okay except Javadoc.

**Comment by dongjoon-hyun** [comment]
This is WIP because this PR is testing Apache Hadoop 3.4.0 RC2.

https://lists.apache.org/thread/cp2fc9w334rkd7ko9dwsodnhfg1sqxhs

**Comment by dongjoon-hyun** [comment]
It seems to be deleted already for RC3.

Screenshot 2024-03-04 at 13 36 06

**Comment by dongjoon-hyun** [comment]
This is WIP because this PR is testing Apache Hadoop 3.4.0 RC3.
- https://lists.apache.org/thread/f8j83jlf0trtnknhfhg235zcn5tk7oqo

**Comment by dongjoon-hyun** [comment]
For the record, I casted +1 for Hadoop 3.4.0 RC3.
- https://lists.apache.org/thread/fwvz7yjw9mq8ns5yq43pzcn3fzjn5fsn

**Comment by dongjoon-hyun** [comment]
Vote passed.
- https://lists.apache.org/list.html?common-dev@hadoop.apache.org

**Review by cxzl25 — APPROVED** [review]
LGTM

**Comment by dongjoon-hyun** [comment]
Javadoc generation passed.

Screenshot 2024-03-19 at 09 45 33

Merged to main for Apache ORC 2.1.0.

**Comment by dongjoon-hyun** [comment]
For the record, I'm also working in the Apache Spark community with the following.
- https://github.com/apache/spark/pull/45583

If needed, we are able to backport this to `branch-2.0` and make Apache ORC 2.0.1 release.

**Comment by dongjoon-hyun** [comment]
cc @wgtmac and @williamhyun , too.

**Pull request closed without merging**
