### PR TITLE
ORC-713: Add Java 15 to GitHub action

### PR DESCRIPTION
**Pull request by williamhyun**
### What changes were proposed in this pull request?
This PR aims to add Java 15 to GitHub action as a preparation for Java 17.

### Why are the changes needed?
Java 17 is the next LTS.

### How was this patch tested?
Pass the GitHub action.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Thank you for making a PR, @williamhyun . Yes, Java 17 is important. It seems to fail on Java 17-ea for some reasons as of now.

**Comment by dongjoon-hyun** [comment]
According to the log, `mockito` can be a root cause. Could you upgrade `mockito-core` first in a separate PR, please?
```
java.lang.NoClassDefFoundError: Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer$3
956
	at org.mockito.internal.creation.jmock.ClassImposterizer.createProxyClass(ClassImposterizer.java:85)
```

**Comment by dongjoon-hyun** [comment]
FYI, I made a PR to `master` to clean up ancient libraries.
- https://github.com/apache/orc/pull/612

**Comment by dongjoon-hyun** [comment]
Could you rebase to the master branch, @williamhyun ?

**Comment by williamhyun** [comment]
Thank you, I rebased @dongjoon-hyun.

**Comment by dongjoon-hyun** [comment]
Interesting. When I run it locally with `17-ea` java test, it works.
```
$ java -version
openjdk version "17-ea" 2021-09-14
OpenJDK Runtime Environment (build 17-ea+3-125)
OpenJDK 64-Bit Server VM (build 17-ea+3-125, mixed mode, sharing)
```

**Comment by dongjoon-hyun** [comment]
You may want to upgrade GitHub Action OS. Currently, it's `18.04` although we specify `ubuntu-latest`.

**Comment by dongjoon-hyun** [comment]
Thank you for updating, @williamhyun !

**Comment by dongjoon-hyun** [comment]
For my previous comment, I created ORC-717. Feel free to pick up it if you have some time.
> According to the log, `mockito` can be a root cause. Could you upgrade `mockito-core` first in a separate PR, please?

**Comment by williamhyun** [comment]
Oops, I created ORC-723 for that. Please see [this](https://github.com/apache/orc/pull/617).

**Comment by dongjoon-hyun** [comment]
No problem. I closed ORC-717 as a duplication of ORC-723 .

**Comment by dongjoon-hyun** [comment]
I merged https://github.com/apache/orc/pull/617 . Could you rebase this PR to the master branch once more, @williamhyun ?

**Comment by williamhyun** [comment]
I rebased, thanks!

**Comment by dongjoon-hyun** [comment]
Thank you for updating. The result is interesting. I'll take a look at that, too.

**Review by dongjoon-hyun — COMMENTED** [review]
The root cause seems to be the `airlift`'s code.
```scala
throw new IncompatibleJvmException("Snappy requires access to java.nio.Buffer raw address field");
```
- https://github.com/airlift/aircompressor/commit/82828ce54bfcec1f4b23cbaa155abbab917ace0f#diff-2b198b97857aeab290b38330d53f6821909a8e3208c49f8b264343084e84b0c6R53

**Comment by dongjoon-hyun** [comment]
FYI, here is the difference.
```
$ jshell
|  Welcome to JShell -- Version 11.0.9
|  For an introduction type: /help intro

jshell> java.nio.Buffer.class.getDeclaredField("address").setAccessible(true)
```

```
$ jshell
|  Welcome to JShell -- Version 17-ea
|  For an introduction type: /help intro

jshell> java.nio.Buffer.class.getDeclaredField("address").setAccessible(true)
|  Exception java.lang.reflect.InaccessibleObjectException: Unable to make field long java.nio.Buffer.address accessible: module java.base does not "opens java.nio" to unnamed module @6d03e736
|        at AccessibleObject.checkCanSetAccessible (AccessibleObject.java:357)
|        at AccessibleObject.checkCanSetAccessible (AccessibleObject.java:297)
|        at Field.checkCanSetAccessible (Field.java:177)
|        at Field.setAccessible (Field.java:171)
|        at (#1:1)
```

**Comment by dongjoon-hyun** [comment]
For this one, shall we add `15` for now and call it a day? We can upgrade it from `15` to `16` and to `17` to track the upstream change and revisit again.

**Comment by williamhyun** [comment]
Sure, @dongjoon-hyun I'll try with Java 15.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you for investigating and working on this, @williamhyun .
GitHub Action passed. Merged to master.

**Pull request merged**
