### PR TITLE
ORC-920: Use junit.version and mockito.version property and bump junit to 5.7.2

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to define `junit.version` and `mockito.version` properties and use it.
In addition, `junit.version` is updated to 5.7.2.

### Why are the changes needed?

Currently, `Dependabot` makes separate PRs per dependencies.
This will advise it to make one PR in the future.

### How was this patch tested?

Pass the CIs.

Closes #831

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @williamhyun

**Review by williamhyun — APPROVED** [review]
+1 LGTM

**Comment by dongjoon-hyun** [comment]
Thank you, @williamhyun !

**Comment by dongjoon-hyun** [comment]
I backported this to branch-1.7 for Apache ORC 1.7.0.

**Pull request merged**
