### PR TITLE
ORC-1408: [C++] Fix row batch not reset if strip doesn't have PRESENT stream.

### PR DESCRIPTION
**Pull request by kaka11chen**
### What changes were proposed in this pull request?

Reset `notNull` data in `ColumnVectorBatch` if strip doesn't have PRESENT stream. 

### Why are the changes needed?

#1466
In ORC, PRESENT stream is optional, and ORC Reader reuse `ColumnVectorBatch` to read data. So if it don't reset `notNull` data in `ColumnVectorBatch`, it will use last `notNull` data incorrectly.

I am a contributor of [apache doris](https://github.com/apache/doris). Doris use the orc cpp lib to build OrcReader/Writer to access hive orc files. This is the PR in doris-thirdparty pull request. https://github.com/apache/doris-thirdparty/pull/55
We are excited to contribute more to the orc cpp library.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Could you add a test case please, @kaka11chen ?

**Comment by wgtmac** [comment]
Thanks for opening the PR. Just curious why it is closed? @kaka11chen

**Comment by kaka11chen** [comment]
> Thanks for opening the PR. Just curious why it is closed? @kaka11chen

I changed the source branch name，the PR is closed automaticity... I will submit a new PR。。。

**Comment by kaka11chen** [comment]
@wgtmac @dongjoon-hyun
The new PR was created, pls review it, thx.
https://github.com/apache/orc/pull/1469

**Pull request closed without merging**
