### PR TITLE
ORC-1422: Setting version to 2.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

`branch-1.9` was created. This PR aims to set version to `2.0.0-SNAPSHOT`.

### Why are the changes needed?

To prepare Apache ORC 2.0.0.

### How was this patch tested?

Pass the CIs.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @williamhyun , @omalley , @wgtmac , @guiyanakuang , @pavibhai , @stiga-huang , @prasanthj

**Review by pavibhai — APPROVED** [review]
+1 LGTM

**Comment by dongjoon-hyun** [comment]
Thank you, @pavibhai !

**Review by guiyanakuang — APPROVED** [review]
+1 LGTM

**Comment by wgtmac** [comment]
Thanks @dongjoon-hyun!

Should we stabilize the file version `UNSTABLE_PRE_2_0` as well?

https://github.com/apache/orc/blob/main/java/core/src/java/org/apache/orc/OrcFile.java#L79

https://github.com/apache/orc/blob/09cd71cd50eece97facfc002f82f7ce7e19a072e/c%2B%2B/src/Common.cc#L135

**Comment by dongjoon-hyun** [comment]
Nice catch. Thank you, @wgtmac .

**Comment by dongjoon-hyun** [comment]
To @wgtmac , I filed a new issue for that because it needs more attentions before the official release of Apache ORC 2.0.
- https://github.com/apache/orc/issues/1499

We will revisit the ORC File Format v2.0 topic in the mailing list first.

Like Apache Parquet or Apache Arrow, I hope we split `ORC Format` from `ORC library`.

**Review by williamhyun — APPROVED** [review]
+1 LGTM

**Comment by dongjoon-hyun** [comment]
Thank you, @williamhyun !

**Comment by dongjoon-hyun** [comment]
Merged to main for Apache ORC 2.0.

**Comment by wgtmac** [comment]
That makes sense. Let us discuss it in the separate topic. @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Thank you. Yes, I'll send out the summary of AS-IS status via email soon.

**Comment by dongjoon-hyun** [comment]
FYI, now we have `2.0.0-SNAPSHOT`.
- https://repository.apache.org/content/groups/snapshots/org/apache/orc/orc-core/2.0.0-SNAPSHOT/

**Pull request closed without merging**
