### PR TITLE
ORC-1306: Fixed indented code style for Java modules

### PR DESCRIPTION
**Pull request by guiyanakuang**
### What changes were proposed in this pull request?
This pr is aimed at fixing all indentation style issues with java modules. And add indentation checking rules to checkstyle.xml.

```xml
    <module name="Indentation">
      <property name="severity" value="error"/>
      <property name="basicOffset" value="2"/>
      <property name="braceAdjustment" value="0"/>
      <property name="caseIndent" value="2"/>
      <property name="throwsIndent" value="2"/>
      <property name="lineWrappingIndentation" value="4"/>
      <property name="arrayInitIndent" value="2"/>
    </module>
```

### Why are the changes needed?
Automated checks save more time and nothing is missed.

### How was this patch tested?
Checking with maven-check-plugin.

### CODE REVIEW

**Comment by deshanxiao** [comment]
Thank you for fix it @guiyanakuang

**Review by wgtmac — APPROVED** [review]
LGTM +1

**Review by dongjoon-hyun — APPROVED** [review]
Nice! It's not worse than I thought.
+100, Thank you.

cc @williamhyun

**Comment by dongjoon-hyun** [comment]
It's merged to `main`.
Could you make a PR to `branch-1.8` too?

**Pull request closed without merging**
