### PR TITLE
ORC-719: Enable UnusedImports rule.

### PR DESCRIPTION
**Pull request by williamhyun**
### What changes were proposed in this pull request?
This PR aims to enable UnusedImports rule. 

### Why are the changes needed?
This will help improve code quality.

### How was this patch tested?
Manual
```
mvn checkstyle:check
```

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. (Pending CIs).
Thank you for working on this area, @williamhyun .

**Comment by dongjoon-hyun** [comment]
To @williamhyun and reviewers, I verified this PR manually like the following by adding an example.
```
$ git diff
diff --git a/java/core/src/java/org/apache/orc/impl/AircompressorCodec.java b/java/core/src/java/org/apache/orc/impl/AircompressorCodec.java
index 3793cba4..6110858b 100644
--- a/java/core/src/java/org/apache/orc/impl/AircompressorCodec.java
+++ b/java/core/src/java/org/apache/orc/impl/AircompressorCodec.java
@@ -23,6 +23,7 @@ import io.airlift.compress.Decompressor;
 import org.apache.orc.CompressionCodec;
 import org.apache.orc.CompressionKind;

+import java.io.File;
 import java.io.IOException;
 import java.nio.ByteBuffer;
```

```
$ mvn checkstyle:check | grep ERROR
Using `mvn` from path: /usr/local/bin/mvn
[ERROR] src/java/org/apache/orc/impl/AircompressorCodec.java:[26,8] (imports) UnusedImports: Unused import - java.io.File.
```

**Comment by dongjoon-hyun** [comment]
Nice. I'll merge this.

**Comment by dongjoon-hyun** [comment]
This is merged via https://github.com/apache/orc/commit/1d9a289af780c1b35f72269012546d892cf91e14

**Comment by dongjoon-hyun** [comment]
Thank you again.

**Comment by pgaref** [comment]
Pretty useful stuff! Thanks @williamhyun and @dongjoon-hyun for working on this :)

**Pull request closed without merging**
