### PR TITLE
ORC-1566: Make Brotli dependency as optional

### PR DESCRIPTION
**Pull request by williamhyun**
### What changes were proposed in this pull request?
This PR aims to make the Brotli dependency as optional.

### Why are the changes needed?
Brotli is not required when Brotli codec is not used. 

### How was this patch tested?
Pass the CIs.

### CODE REVIEW

**Comment by williamhyun** [comment]
cc: @deshanxiao @dongjoon-hyun

**Review by dongjoon-hyun — APPROVED** [review]
Thank you, @williamhyun !

+1, LGTM.

**Comment by deshanxiao** [comment]
+1 Thanks @williamhyun

**Comment by dongjoon-hyun** [comment]
Merged to main for Apache ORC 2.0.0.

Thank you, @williamhyun and @deshanxiao .

**Pull request closed without merging**
