### PR TITLE
Orc-280: [C++] use Z_PREFIX if zlib requires it

### PR DESCRIPTION
**Pull request by rip-nsk**

### CODE REVIEW

**Comment by rip-nsk** [comment]
linux clang build broken due to new version of compiler (5.0.0)
This is not related to proposed changes.

**Comment by omalley** [comment]
Which platforms need this? I assume it would only be needed when you are using the system zlib.

**Comment by rip-nsk** [comment]
Any platform, if corresponding zlib used (by ZLIB_HOME) to build ORC.

**Comment by omalley** [comment]
Do any of the platforms build their vendor zlib library with Z_PREFIX? Or is it just custom installations?

**Comment by rip-nsk** [comment]
It is custom installation. In my environment I have to use prebuilt static "zprefixed" zlib.
But it is general case since custom zlib can be used via ZLIB_HOME.

**Pull request closed without merging**
