### PR TITLE
ORC-1516: Fixed minor typo in IOUtils

### PR DESCRIPTION
**Pull request by mystic-lama**
### What changes were proposed in this pull request?
The PR fixes a minor typo in comments section in org.apache.orc.impl.IOUtils at Line 127.

### Why are the changes needed?
The changes are more cosmetic and corrects the statement

### How was this patch tested?
Change is within code comment, no Test updates needed.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Is this the last typo in `IOUtils.java`? Could you take a look once more?

**Comment by mystic-lama** [comment]
@dongjoon-hyun I did not check the complete file, I was looking at this function and saw it. Let me relook at whole file

**Comment by mystic-lama** [comment]
Done. Found one more 🤦 

@dongjoon-hyun Nice catch and Thanks for watching over 🙇‍♂️

**Comment by dongjoon-hyun** [comment]
Thank you!

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Pull request closed without merging**
