### PR TITLE
ORC-1357: Handle missing compression block size

### PR DESCRIPTION
**Pull request by HuwCampbell**
### What changes were proposed in this pull request?

The C++ implementation handles when the postscript doesn't include compressionBlockSize by checking if it is set and using 256 * 1024 if it is not.

As compressionBlockSize is optional this means valid files couldn't be read with the Java implementation. This change brings the Java implemenation in line with C++ by first checking and using the same default value.

### Why are the changes needed?

Some files which can be read by C++ fail to be read when compression is enabled in the Java implementation because it uses a default buffer of size 0 (which is just an arbitrary protobuf 'nil' conversion).

### How was this patch tested?

New file / test case added which failed to read before in Java but could be read by C++.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you for making a PR, @HuwCampbell .
Could you add a test case to validate your PR, please?

**Comment by HuwCampbell** [comment]
No problem.

**Review by dongjoon-hyun — COMMENTED** [review]
This seems to cause test failures in the existing unit tests. Could you adjust them accordingly?
```
[ERROR] Failures:
[ERROR]   TestVectorOrcFile.testEmptyFile:1498 expected: <0> but was: <262144>
[ERROR]   TestVectorOrcFile.testEmptyFile:1498 expected: <0> but was: <262144>
[ERROR]   TestVectorOrcFile.testEmptyFile:1498 expected: <0> but was: <262144>
[ERROR]   TestVectorOrcFile.testZeroByteOrcFile:4129 expected: <0> but was: <262144>
```

**Comment by HuwCampbell** [comment]
Sure

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM (Pending CIs). Thank you, @HuwCampbell .

**Comment by dongjoon-hyun** [comment]
I added to the Apache ORC contributor group and assigned ORC-1357 to you.
Welcome to the Apache ORC community, @HuwCampbell .

**Comment by dongjoon-hyun** [comment]
I backported this to branch-1.8 for Apache ORC 1.8.3 via 2aec2413cd54ea1f04e6772145d008e203acf1c9

**Comment by emkornfield** [comment]
It looks like C++  uses 64K is there reason 256K for this PR?

**Pull request merged**
