### PR TITLE
ORC-934: Add integration tests for Java bench

### PR DESCRIPTION
**Pull request by williamhyun**
### What changes were proposed in this pull request?
This PR aims to add integration tests for Java bench. 

### Why are the changes needed?
To prevent further regressions. 

### How was this patch tested?
Pass the CIs.

### CODE REVIEW

**Comment by williamhyun** [comment]
cc: @dongjoon-hyun

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. It's a nice addition. Thank you so much, @williamhyun !
(Pending CIs)

**Comment by dongjoon-hyun** [comment]
Oh, interesting. Your PR reveals that our benchmark fails at Java 16+. This is really an invaluable test coverage!
```
[WARN ] Problem opening checksum file: data/generated/sales/json.snappy.  Ignoring exception: 
java.io.EOFException
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:203)
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:172)
	at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSInputChecker.<init>(ChecksumFileSystem.java:151)
	at org.apache.hadoop.fs.ChecksumFileSystem.open(ChecksumFileSystem.java:346)
	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:769)
	at org.apache.orc.bench.core.convert.json.JsonReader.<init>(JsonReader.java:59)
	at org.apache.orc.bench.core.convert.GenerateVariants.createFileReader(GenerateVariants.java:90)
	at org.apache.orc.bench.core.convert.ScanVariants.run(ScanVariants.java:88)
	at org.apache.orc.bench.core.Driver.main(Driver.java:64)
Error: Exception in thread "main" com.google.gson.JsonIOException: java.io.EOFException: End of input at line 1 column 1
	at com.google.gson.JsonStreamParser.hasNext(JsonStreamParser.java:109)
	at org.apache.orc.bench.core.convert.json.JsonReader.nextBatch(JsonReader.java:76)
	at org.apache.orc.bench.core.convert.ScanVariants.run(ScanVariants.java:92)
	at org.apache.orc.bench.core.Driver.main(Driver.java:64)
Caused by: java.io.EOFException: End of input at line 1 column 1
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1377)
	at com.google.gson.stream.JsonReader.consumeNonExecutePrefix(JsonReader.java:1514)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:523)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:414)
	at com.google.gson.JsonStreamParser.hasNext(JsonStreamParser.java:105)
	... 3 more
```

**Comment by dongjoon-hyun** [comment]
The error comes here. Let me take a look at this.
- https://github.com/airlift/aircompressor/blob/master/src/main/java/io/airlift/compress/snappy/UnsafeUtil.java#L52

**Comment by dongjoon-hyun** [comment]
The changes look feasible. Let's wait and see the CI results.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

I checked the log at GitHub Action Java 16.
```
Test project /home/runner/work/orc/orc/build
    Start 1: orc-test
1/7 Test #1: orc-test .........................   Passed    5.13 sec
    Start 2: java-test
2/7 Test #2: java-test ........................   Passed  187.39 sec
    Start 3: java-examples-test
3/7 Test #3: java-examples-test ...............   Passed    0.64 sec
    Start 4: java-tools-test
4/7 Test #4: java-tools-test ..................   Passed    0.14 sec
    Start 5: java-bench-gen-test
5/7 Test #5: java-bench-gen-test ..............   Passed    2.16 sec
    Start 6: java-bench-scan-test
6/7 Test #6: java-bench-scan-test .............   Passed    1.46 sec
    Start 7: tool-test
7/7 Test #7: tool-test ........................   Passed   12.19 sec

100% tests passed, 0 tests failed out of 7

Total Test time (real) = 209.17 sec
Built target test-out
```

**Comment by dongjoon-hyun** [comment]
Merged to main/1.7.

**Pull request merged**
