### PR TITLE
ORC-258: [C++] Incorrect Decimal constructor

### PR DESCRIPTION
**Pull request by wgtmac**
1. Fixed constructor Decimal::Decimal(const std::string& str).
2. Added test cases to verify it.

### CODE REVIEW

**Comment by wgtmac** [comment]
@majetideepak @omalley Please take a look when you have time, thanks!

**Comment by majetideepak** [comment]
Thanks @wgtmac

**Comment by wgtmac** [comment]
@majetideepak Do you have time to review/merge my previous pull request for ORC-224: [https://github.com/apache/orc/pull/149](https://github.com/apache/orc/pull/149) again? You have signed off long long ago. Thanks!

**Comment by majetideepak** [comment]
@wgtmac will do. I will make another pass today and merge it. Thanks!

**Pull request closed without merging**
