### PR TITLE
ORC-776: Include source jars during publishing snapshot

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to include `source` jars at snapshots. We need this patch for all branches (master/branch-1.6/branch-1.5).
- https://repository.apache.org/content/repositories/snapshots/org/apache/orc/orc-core/

### Why are the changes needed?

Currently, snapshot artifacts doesn't have source jars while the release artifacts have them.
`source` jars are crucial during debugging with snapshot jars.

### How was this patch tested?

Manually.

**BEFORE**
```
$ mvn install -DskipTests
$ ls -al ~/.m2/repository/org/apache/orc/orc-core/1.7.0-SNAPSHOT
total 2800
drwxrwxr-x 2 dongjoon dongjoon    4096 Mar 27 18:59 .
drwxrwxr-x 3 dongjoon dongjoon    4096 Mar 27 18:59 ..
-rw-rw-r-- 1 dongjoon dongjoon     912 Mar 27 18:59 maven-metadata-local.xml
-rw-rw-r-- 1 dongjoon dongjoon 1029565 Mar 27 18:59 orc-core-1.7.0-SNAPSHOT.jar
-rw-rw-r-- 1 dongjoon dongjoon 1808265 Mar 27 18:59 orc-core-1.7.0-SNAPSHOT-nohive.jar
-rw-rw-r-- 1 dongjoon dongjoon    5210 Mar 23 15:47 orc-core-1.7.0-SNAPSHOT.pom
-rw-rw-r-- 1 dongjoon dongjoon     237 Mar 27 18:59 _remote.repositories
```

**AFTER**
```
$ mvn install -DskipTests
$ ls -al ~/.m2/repository/org/apache/orc/orc-core/1.7.0-SNAPSHOT
total 6872
drwxr-xr-x  9 dongjoon  dongjoon      288 Mar 27 19:00 .
drwxr-xr-x  4 dongjoon  dongjoon      128 Mar 27 19:00 ..
-rw-r--r--  1 dongjoon  dongjoon      318 Mar 27 19:00 _remote.repositories
-rw-r--r--  1 dongjoon  dongjoon     1327 Mar 27 19:00 maven-metadata-local.xml
-rw-r--r--  1 dongjoon  dongjoon  1808265 Mar 27 19:00 orc-core-1.7.0-SNAPSHOT-nohive.jar
-rw-r--r--  1 dongjoon  dongjoon   443706 Mar 27 19:00 orc-core-1.7.0-SNAPSHOT-sources.jar
-rw-r--r--  1 dongjoon  dongjoon   210828 Mar 27 19:00 orc-core-1.7.0-SNAPSHOT-test-sources.jar
-rw-r--r--  1 dongjoon  dongjoon  1029565 Mar 27 19:00 orc-core-1.7.0-SNAPSHOT.jar
-rw-r--r--  1 dongjoon  dongjoon     5210 Mar 25 22:49 orc-core-1.7.0-SNAPSHOT.pom
```

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @pgaref and @omalley .
Could you review this please when you have some time?
During the official release cycle, we are using the maven-source-jar plugin in Apache pom file. So, we don't need this. However, for snapshot publishing, we need this PR.

**Comment by dongjoon-hyun** [comment]
Could you review this, @wgtmac ?

**Review by wgtmac — APPROVED** [review]
+1 LGTM

**Comment by dongjoon-hyun** [comment]
Thank you so much, @wgtmac !

**Comment by dongjoon-hyun** [comment]
So far, the result looks good at 1.7.0-SNAPSHOT. So, I backported this to branch-1.6/1.5.
- https://repository.apache.org/content/repositories/snapshots/org/apache/orc/orc-core/

**Pull request merged**
