### PR TITLE
MINOR: Fix Patched Base doc in specification

### PR DESCRIPTION
**Pull request by Jefffrey**
### What changes were proposed in this pull request?

Fix patched base specification to state that only 5% of values are patched, not 10%

### Why are the changes needed?

According to implementation:

https://github.com/apache/orc/blob/0828c2ff114f30c84e4a23fd42ed58c6615c6f97/java/core/src/java/org/apache/orc/impl/RunLengthIntegerWriterV2.java#L535-L550

- Also 10% of 512 doesn't fit in max patch list length of 31

Also fix some formatting issues.

Before:

image

After:

image

### How was this patch tested?

N/A

### Was this patch authored or co-authored using generative AI tooling?

No

### CODE REVIEW

**Review by wgtmac — APPROVED** [review]
+1

**Comment by wgtmac** [comment]
@dongjoon-hyun We have duplicate content at https://github.com/apache/orc-format/tree/main/specification. Is it inevitable to maintain the two copies unless we have a orc-site repo?

**Comment by dongjoon-hyun** [comment]
> @dongjoon-hyun We have duplicate content at https://github.com/apache/orc-format/tree/main/specification. Is it inevitable to maintain the two copies unless we have a orc-site repo?

Yes, it looks inevitable if we want to have this documentation in our website. Please let me know if you have an idea to mitigate this, @wgtmac .

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
Merged to main.

**Pull request closed without merging**
