### PR TITLE
ORC-1213: [C++] Use `https` in `ThirdpartyToolchain.cmake`

### PR DESCRIPTION
**Pull request by dbaxa**
Update some download links from using http & ftp to https

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you for making a PR, @dbaxa .

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.
Merged to main/1.8/1.7.

**Comment by dongjoon-hyun** [comment]
Welcome to Apache ORC community and thank you for your first contribution, @dbaxa .
Do you have Apache JIRA id? I need to assign ORC-1213 to you.

**Comment by dbaxa** [comment]
Hi @dongjoon-hyun , it should be `dblack`.

**Comment by dongjoon-hyun** [comment]
Thank you. ORC-1213 is assigned to `dblack` now. :)

Screen Shot 2022-07-12 at 5 05 38 PM
.

**Pull request closed without merging**
