### PR TITLE
ORC-46. Reserve CompressionKind values for LZ4 and ZSTD.

### PR DESCRIPTION
**Pull request by electrum**

### CODE REVIEW

**Comment by omalley** [comment]
This seems reasonable. Are you working on implementing the compression? I'd love to get the integration in so that others could experiment with them.

**Comment by electrum** [comment]
We will implement them in Presto using this compression code (zstd coming soon): https://github.com/airlift/aircompressor

**Comment by omalley** [comment]
A couple of thoughts:
* So Presto has a writer now? If so, we should extend the WriterVersion with a new id for it so that we can handle bugs that are specific to that implementation.
* I assume you'll follow the same compression block structure that we used with zlib and snappy. (Three bytes of header followed by the untagged compressed bytes.) I'm very concerned that we don't break compatibility with the C++ and Java readers.
* That is *really* cool that there is a pure Java LZO, Snappy, and LZ4 implementation that is Apache licensed. Does it have a release that is pushed to Maven central?

**Comment by martint** [comment]
> So Presto has a writer now? If so, we should extend the WriterVersion with a new id for it so that we can handle bugs that are specific to that implementation.

We're going to start working on a writer soon.

> I assume you'll follow the same compression block structure that we used with zlib and snappy. (Three bytes of header followed by the untagged compressed bytes.) I'm very concerned that we don't break compatibility with the C++ and Java readers.

Yeah, most likely.

> That is really cool that there is a pure Java LZO, Snappy, and LZ4 implementation that is Apache licensed. Does it have a release that is pushed to Maven central?

http://search.maven.org/#artifactdetails%7Cio.airlift%7Caircompressor%7C0.3%7Cjar

**Pull request closed without merging**
