### PR TITLE
ORC-851: Fix CNFE in ORC tools uber jar

### PR DESCRIPTION
**Pull request by williamhyun**
### What changes were proposed in this pull request?
This PR aims to fix CNFE in ORC tools uber jar. 

### Why are the changes needed?
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/conf/Configuration
	at org.apache.orc.tools.Driver.main(Driver.java:101)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.conf.Configuration
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 1 more
```
### How was this patch tested?
Manual.

### CODE REVIEW

**Comment by williamhyun** [comment]
CC: @belugabehr @dongjoon-hyun

**Review by pgaref — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
Thank you so much, @williamhyun and @pgaref !

**Comment by belugabehr** [comment]
I'm not sure I understand the change.

> compile This is the default scope, used if none is specified.

I do not expect this patch to have any affect on the build. Can you please explain?

**Comment by dongjoon-hyun** [comment]
@belugabehr . Your PR changes `compile` dependency to `provided` dependency. That's the regression which @williamhyun found. The ORC tools uber jar should have all required jars.

Actually, it's my bad. I should have checked when I reviewed your PR, @belugabehr .

**Review by dongjoon-hyun — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
@belugabehr . Please check the parent pom here.
- https://github.com/apache/orc/blob/main/java/pom.xml#L525
- https://github.com/apache/orc/blob/main/java/pom.xml#L754

**Comment by belugabehr** [comment]
Hmm. I see. My apologies and thanks for the catch.  However, maybe I'm missing something obvious, but this PR simply adds the "compile" scope to something that previously had no scope (default: compile).  It does not change: provided => compile.

**Comment by dongjoon-hyun** [comment]
@belugabehr . Do you know Maven POM inheritance? Here is the reference for you.
- https://maven.apache.org/pom.html#inheritance

**Comment by dongjoon-hyun** [comment]
BTW, no worries, @belugabehr . This is not released yet. It's lucky to find this earlier stage.

**Comment by belugabehr** [comment]
Hey, ya, I'm quite familiar. I was just looking about to look that up regarding scope. I didn't not consider scope inheritance here. Again, sorry for the inconvenience.

**Comment by dongjoon-hyun** [comment]
Merged to main. Thank you, @williamhyun and all.

**Comment by dongjoon-hyun** [comment]
I backported #708 and this together to branch-1.7.

**Pull request merged**
