### PR TITLE
ORC-1140: Documented background and benchmarks for ORC-1136

### PR DESCRIPTION
**Pull request by pavibhai**
### What changes were proposed in this pull request?
This includes benchmark results and documentation for ORC-1136

### Why are the changes needed?
For documentation

### How was this patch tested?
Documentation related changes only

### CODE REVIEW

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
This seems to GitHub-only documentation. Could you revise in order to publish this to Apache ORC website, @pavibhai ?

**Comment by dongjoon-hyun** [comment]
Also, cc @omalley

**Comment by dongjoon-hyun** [comment]
Gentle ping.

**Comment by pavibhai** [comment]
> This seems to GitHub-only documentation. Could you revise in order to publish this to Apache ORC website, @pavibhai ?

Thanks @dongjoon-hyun this is a good point. I see that currently we don't showcase any of the design docs or benchmarks on the site. I agree that this is more useful on the site especially the benchmarks.

@omalley any suggestions/inputs on this?

**Comment by omalley** [comment]
I'm leaning toward having an index.md for develop/design that covers all of the design & benchmark stuff. We can link that off of develop/index.md.

**Comment by pavibhai** [comment]
@dongjoon-hyun I have made the required changes to have this accessible from the ORC Site. Please check and let me know.

**Comment by dongjoon-hyun** [comment]
+1, LGTM from my side.

**Pull request merged**
