### PR TITLE
ORC-950: Bump aircompressor to 0.20

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to bump `aircompressor` to 0.20.

### Why are the changes needed?

To bring the following patch.
- https://github.com/airlift/aircompressor/commit/5e353d056222ea633b79dbead71137d85934ca96

### How was this patch tested?

Pass the Cis.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @williamhyun

**Comment by dongjoon-hyun** [comment]
Gentle ping, @williamhyun ~

**Review by williamhyun — APPROVED** [review]
+1 LGTM

**Comment by dongjoon-hyun** [comment]
Thank you for your review and merging.

**Pull request merged**
