### PR TITLE
ORC-1416: Upgrade Jackson dependency to 2.14.2 in `bench` module

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to upgrade Jackson dependency to 2.14.2 in bench module.

### Why are the changes needed?

To match with Apache Spark 3.4.0.

### How was this patch tested?

Pass the CIs.

Closes #1476

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @williamhyun

**Comment by dongjoon-hyun** [comment]
Also, cc @deshanxiao since he is the author of ORC-1414
- #1473

**Comment by deshanxiao** [comment]
+1
Thank you @dongjoon-hyun

**Review by williamhyun — APPROVED** [review]
+1 LGTM

**Comment by dongjoon-hyun** [comment]
Thank you, @deshanxiao and @williamhyun .

**Pull request closed without merging**
