### PR TITLE
ORC-1098: [C++] Support specifying type ids or column names in cpp tools

### PR DESCRIPTION
**Pull request by stiga-huang**
### What changes were proposed in this pull request?

This is a follow-up task of #921. Currently we have options for the tools to work on specified top-level column fields. However, ACID ORC files usually have nested structure. We need the type ids to specify nested columns. As an extension, adding support for column names will also be helpful. So we don't need to manually convert column names to type ids. Also reports the valid values when an invalid column name is given.

This PR extracts the option parsing codes into ToolsHelper. So similiar cpp tools can share the same option set.

### Why are the changes needed?

It makes the tools more useful in practice.

### How was this patch tested?

Added unit tests for the new options.

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Thank you so much for the PR, @stiga-huang .

Could you review this please, @wgtmac ?

And, if possible, could you participate the on-going Apache ORC 1.6.13 vote, @stiga-huang and @wgtmac ?

**Comment by stiga-huang** [comment]
Thank @dongjoon-hyun! Just voted.

**Comment by dongjoon-hyun** [comment]
Thank you so much for your participation, @stiga-huang .

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @stiga-huang .
Merged to main for Apache ORC 1.8.

**Comment by dongjoon-hyun** [comment]
@stiga-huang . After reviewing this PR once more and testing on `branch-1.7`, I decided to re-target this to v1.7.3 instead of v1.8.0 because this is a safe `tools` only PR and the change on `Reader.cc` is also about `ParseError` message instead of a `core` code change. Thank you again.

**Pull request merged**
