### PR TITLE
ORC-761: Replace MAINTAINER command with LABEL command

### PR DESCRIPTION
**Pull request by yuokada**
### What changes were proposed in this pull request?

- Replace MAINTAINER command with LABEL command.

### Why are the changes needed?

MAINTAINER command is deprecated since docker 1.13 or later. 
https://docs.docker.com/engine/reference/builder/#maintainer-deprecated

### How was this patch tested?

- Confirmed that `Dockerfile`s are built successfully with `reinit.sh`

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @yuokada .
~Merged to master/1.6.~

**Comment by dongjoon-hyun** [comment]
Ur, @yuokada .
This should have an independent ORC JIRA id.

**Comment by yuokada** [comment]
I will file a ticket.

**Comment by dongjoon-hyun** [comment]
Yep. I'll merge after the title is updated with the new ORC JIRA id.

**Comment by yuokada** [comment]
@dongjoon-hyun 
Filed: https://issues.apache.org/jira/browse/ORC-761

ANd also, I replaced in `site/Dockerfile`.
https://github.com/apache/orc/pull/656/commits/2c082bafba13dfb435399a50f62503bef459946d

**Review by dongjoon-hyun — APPROVED** [review]
Thanks for the last commit.
+1, LGTM again for the new changes.

**Comment by yuokada** [comment]
@dongjoon-hyun Thanks for your reviewing and merging.

**Pull request merged**
