### PR TITLE
ORC-681: Upgrade commons-codec to 1.15

### PR DESCRIPTION
**Pull request by williamhyun**
### What changes were proposed in this pull request?
Upgrade commons-codec to version 1.15.

### Why are the changes needed?
This will bring the latest bug fixes. 

### How was this patch tested?
Pass the CI.

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
This looks safe for Apache ORC 1.7 because Apache Hadoop 3.4 is already using 1.14.
- https://github.com/apache/hadoop/pull/2000

**Comment by dongjoon-hyun** [comment]
Thank you, @williamhyun .

Although Apache ORC's `commons-codec` 1.4 is consistent with Apache Hive 2.3.7/Apache Hadoop 2.4.7, Apache Hive 3.1.2 is using `commons-codec` 1.7 and Apache Hadoop 3.2/3.4 is using `commons-codec` 1.11 and 1.14 respectively. Given that, this PR looks safe and proper for Apache ORC 1.7.0.

@omalley and @wgtmac .

**Comment by dongjoon-hyun** [comment]
Could you try to upgrade `commons-lang` to `commons-lang3` in a separate PR, @williamhyun ?

**Comment by williamhyun** [comment]
Sure, I'll try @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Thank you, @williamhyun . Merged to master for Apache ORC 1.7.0.

**Pull request merged**
