### PR TITLE
MINOR: Update Yiqun Zhang from the committer to PMC in site

### PR DESCRIPTION
**Pull request by guiyanakuang**
### What changes were proposed in this pull request?
This PR aims to update Yiqun Zhang from the committer to PMC in site.

### Why are the changes needed?
N/A

### How was this patch tested?
N/A

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

To @guiyanakuang , feel free to merge this PR.

cc @williamhyun for the News page.

**Comment by dongjoon-hyun** [comment]
One more thing, please try to publish your update to the official website. You need to do it with Docker. :)
- https://orc.apache.org/develop/committers/

**Comment by guiyanakuang** [comment]
Okay, let me try to publish it. 🙂

**Comment by dongjoon-hyun** [comment]
Please check the generated files before committing at `asf-site` branch. You need to update only a single HTML file.

**Comment by guiyanakuang** [comment]
Don't worry, I will operate with great care.

**Comment by guiyanakuang** [comment]
At first I thought I needed to publish the html to one of the apache web servers, but instead I just committed it to the asf-site branch and it was done. Please help to double check my first publish. @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
I double-checked it. You did correctly at both commit and webpage, @guiyanakuang .
- https://github.com/apache/orc/commit/458005d70bac874c6ea86c4f699bc599cbdfa712

I can see your new role.
Screen Shot 2022-05-07 at 9 57 14 PM

**Pull request merged**
