### PR TITLE
ORC-1050: Update ORC site README.md and release process page

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to update ORC release and publish process pages.

### Why are the changes needed?

The current web content is outdated.

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @williamhyun and @guiyanakuang 

While reviewing @williamhyun 's PR, I realized that our website README and `make-release` page is outdated. This is the up-to-date process I used during Apache ORC 1.7.1 release.

**Comment by dongjoon-hyun** [comment]
Gentle ping, @williamhyun and @guiyanakuang .

**Comment by guiyanakuang** [comment]
@dongjoon-hyun It looks good, but the url of the archive seems to be out of date in make-release.md, I think it can be updated together

**Review by williamhyun — APPROVED** [review]
+1 LGTM

**Comment by dongjoon-hyun** [comment]
Thank you so much for review, @guiyanakuang and @williamhyun .

To @guiyanakuang . The archive link style is correct. I used the following for Apache ORC 1.7.1rc0. The link was just removed when I convert the release candidate tag, `release-1.7.1rc0`, to the official release tag, `rel/release-1.7.1`.

```
curl -LO https://github.com/apache/orc/archive/release-1.7.1rc0.tar.gz
```

**Comment by dongjoon-hyun** [comment]
Merged to main for next release.

**Comment by guiyanakuang** [comment]
I get it

**Pull request merged**
