### PR TITLE
ORC-1009: [C++] Missing string include causes build failure with MSVC++

### PR DESCRIPTION
**Pull request by noirello**
### What changes were proposed in this pull request?
Include string in ExpressionTree.hh.

### Why are the changes needed?
Without it the library cannot be built on Windows with newer msvc++ compiler (version 19.29).

### How was this patch tested?
Manually, successfully building the library on Windows on a local machine.

### CODE REVIEW

**Comment by wgtmac** [comment]
Thanks for the quick fix @noirello !  I will hold this fix until https://github.com/apache/orc/pull/918 is merged to make AppVeyor build happy.

**Comment by dongjoon-hyun** [comment]
#918 is merged now. Feel free to proceed.
BTW, I'm not sure how to re-trigger `AppVeyor`.

**Comment by dongjoon-hyun** [comment]
Thank you, @noirello and @wgtmac . BTW, if this is for newer VC++, do we need this at main/branch-1.7/branch-1.6?

**Comment by noirello** [comment]
@dongjoon-hyun I just rebased on the current main branch to include #918.
The C++ SearchArgument feature is not included in branch-1.6, but I think it would be great to include this fix in the main and branch-1.7.

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you for the confirmation, @noirello and @wgtmac .
Merged to main/1.7.

**Pull request merged**
