### PR TITLE
ORC-1292: Add paragraph in java documentation

### PR DESCRIPTION
**Pull request by deshanxiao**
### What changes were proposed in this pull request?
This PR is aimed to add paragraph in java documentation.

### Why are the changes needed?
In java doc, blank line will be ignored. We need to add "\<p\>" to display it. #1278 

### How was this patch tested?
UT

### CODE REVIEW

**Comment by deshanxiao** [comment]
CC @dongjoon-hyun

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you so much, @deshanxiao .

**Comment by dongjoon-hyun** [comment]
cc @williamhyun , too

**Comment by deshanxiao** [comment]
@dongjoon-hyun Thank you for adding a jira.

**Pull request closed without merging**
