### PR TITLE
ORC-802: Make Maven Minimum 3.6.0

### PR DESCRIPTION
**Pull request by belugabehr**

### CODE REVIEW

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
Hi, @belugabehr .
Apache ORC community provides `Maven Wrapper`, `mvnw`. Could you try that?

**Comment by belugabehr** [comment]
@dongjoon-hyun Thanks for the update.

I have verified that the script does indeed build the project, but I've never seen such a setup before (and it's not documented in the README).  What is the value of doing it this way?  It is not expected at all.

If this is absolutely the preferred way, I can update the docs to mention this. 

Thanks!

**Comment by dongjoon-hyun** [comment]
Thanks. +1 for switching to a doc-only updating PR.

**Comment by dongjoon-hyun** [comment]
I'll close this for now. Please feel free to reopen this when you are ready.

**Pull request closed without merging**
