### PR TITLE
ORC-771: ORC timestamp consistency Test for sql.Timestamps close to epoch

### PR DESCRIPTION
**Pull request by pgaref**
### What changes were proposed in this pull request?
ORC-763 has a long discussion about the sql.Timestamp bug and how ORC goes around it.

### Why are the changes needed?
This ticket introduces a Test to ensure consistency with the expected behaviour – as we have on C++ side of things.

### How was this patch tested?
TestVectorOrcFile.testTimestampBug

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Thank you for working on this, @pgaref .

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM.

**Comment by dongjoon-hyun** [comment]
cc @wgtmac

**Comment by dongjoon-hyun** [comment]
Merged to master/1.6.

**Comment by pgaref** [comment]
Thanks!

**Pull request merged**
