### PR TITLE
ORC-875: Add GitHub Action job for Windows Server 2019

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to add a test coverage for Windows on GitHub Action additionally.

### Why are the changes needed?

This PR aims to replace `AppVeyor` with GitHub Action eventually.

**AS IS(AppVeyor)**

https://github.com/apache/orc/blob/ae660f3006cae145d0db7a897fd81fe94029c0b2/appveyor.yml#L18-L41

**THIS PR(GitHub Action)**

https://github.com/apache/orc/runs/4662857757?check_suite_focus=true

```
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe - skipped
-- compiler MSVC version 19.0.24245.0
...
Test project D:/a/orc/orc/build
    Start 1: orc-test
1/1 Test #1: orc-test .........................   Passed   61.99 sec
```

### How was this patch tested?

Pass the GitHub Action with newly add Windows job.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @williamhyun . Could you review this?
We are going to run and monitor this job in order to decide the removal of `AppVeyor`.

**Review by williamhyun — APPROVED** [review]
+1 LGTM

**Comment by dongjoon-hyun** [comment]
Thank you so much, @williamhyun .

**Comment by dongjoon-hyun** [comment]
I backported this to branch-1.7 too.

**Pull request merged**
