### PR TITLE
ORC-676. Add getRawDataSizeFromColIndices back to ReaderImpl

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to add `getRawDataSizeFromColIndices` back to `ReaderImpl`.

### Why are the changes needed?

This helps the migration path from Apache Orc 1.5 to 1.6+

### How was this patch tested?

Pass the newly added test case.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Could you review this please, @omalley ?

**Comment by dongjoon-hyun** [comment]
Could you review this, @wgtmac ?

**Review by wgtmac — APPROVED** [review]
LGTM +1

**Comment by dongjoon-hyun** [comment]
Thank you so much, @wgtmac !

**Comment by dongjoon-hyun** [comment]
For Apache Orc 1.6.6, I cherry-picked to branch-1.6 and pushed after testing.

**Pull request merged**
