### PR TITLE
ORC-1751: [C++] fix syntax error in ThirdpartyToolchain

### PR DESCRIPTION
**Pull request by luffy-zh**
What changes were proposed in this pull request?
fix syntax error in ThirdpartyToolchain

Why are the changes needed?
Handle the issue discussed [here]( https://github.com/apache/arrow/pull/43417)

How was this patch tested?
Test it locally

Was this patch authored or co-authored using generative AI tooling?
NO

### CODE REVIEW

**Review by dongjoon-hyun — COMMENTED** [review]
Is this all we need, @luffy-zh ?

**Review by wgtmac — APPROVED** [review]
+1

Thanks @luffy-zh!

cc @kou @raulcd if there is anything missing

**Review by raulcd — APPROVED** [review]
This looks good to me. I think the underlying issue which I had to use this patch:
```diff
diff --git a/cmake_modules/ThirdpartyToolchain.cmake b/cmake_modules/ThirdpartyToolchain.cmake
index aa520ff..7bd75d1 100644
--- a/cmake_modules/ThirdpartyToolchain.cmake
+++ b/cmake_modules/ThirdpartyToolchain.cmake
@@ -416,6 +416,18 @@ endif ()
 if (NOT "${PROTOBUF_HOME}" STREQUAL "" OR ORC_PACKAGE_KIND STREQUAL "conan")
   find_package (Protobuf REQUIRED)
   set(PROTOBUF_VENDORED FALSE)
+  if (Protobuf_FOUND AND NOT PROTOBUF_STATIC_LIB)
+    get_target_property (target_type protobuf::libprotobuf TYPE)
+    if (target_type STREQUAL "STATIC_LIBRARY")
+        set(PROTOBUF_STATIC_LIB protobuf::libprotobuf)
+    endif ()
+  endif()
+  if (Protobuf_FOUND AND NOT PROTOC_STATIC_LIB)
+    get_target_property (target_type protobuf::libprotoc TYPE)
+    if (target_type STREQUAL "STATIC_LIBRARY")
+        set (PROTOC_STATIC_LIB protobuf::libprotoc)
+    endif ()
+  endif()
 else ()
   set(PROTOBUF_PREFIX "${THIRDPARTY_DIR}/protobuf_ep-install")
   set(PROTOBUF_INCLUDE_DIR "${PROTOBUF_PREFIX}/include")
```
might have already been fixed as suggested by @kou at: https://github.com/apache/orc/pull/1963

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you, @luffy-zh , @wgtmac , @raulcd .
Merged to main/2.0 for Apache ORC 2.0.2.

**Comment by dongjoon-hyun** [comment]
Merged to main.

There exists a conflict on `branch-2.0`. Could you make a backporting PR to `branch-2.0`, @luffy-zh ?

**Review by kou — COMMENTED** [review]
+1

Sorry for late review.

**Comment by luffy-zh** [comment]
> Merged to main.
> 
> There exists a conflict on `branch-2.0`. Could you make a backporting PR to `branch-2.0`, @luffy-zh ?

OK, I will make a backporting PR to branch-2.0 later.

**Pull request closed without merging**
