### PR TITLE
ORC-730: Add website link and description to GitHub page

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to add to `https://github.com/apache/orc`.
- website link
- project description

### Why are the changes needed?

To help a better UX. This will be displayed here (the red box).
Screen Shot 2021-01-12 at 8 36 31 PM

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @pgaref

**Comment by dongjoon-hyun** [comment]
The `Travis CI` failure is irrelevant.

**Comment by pgaref** [comment]
+1 thanks @dongjoon-hyun !

**Comment by dongjoon-hyun** [comment]
Thank you so much, @pgaref !

**Pull request merged**
