### PR TITLE
ORC-1738: [C++] Fix wrong Int128 maximum value

### PR DESCRIPTION
**Pull request by letian-jiang**
### Why are the changes needed?

The low part of Int128::maximumValue is wrong. In hex format, it should be 0xffffffffffffffff rather than 0xfffffffffffffff, in which one f is dropped by mistake. 

### How was this patch tested?

I have added the relevant unit tests.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Review by wgtmac — APPROVED** [review]

**Review by ffacs — APPROVED** [review]
LGTM, +1

**Comment by ffacs** [comment]
It's an issue from day one; perhaps we should consider cherry-picking it into branch-1.0.

**Review by dongjoon-hyun — APPROVED** [review]
Yes, +1 for backporting for all live release branches.
- master
- branch-2.0
- branch-1.9
- branch-1.8
- branch-1.7

**Comment by dongjoon-hyun** [comment]
Welcome to the Apache ORC community, @letian-jiang .
I added you to the Apache ORC contributor group and assigned ORC-1738 to you.
Thank you again!

**Comment by dongjoon-hyun** [comment]
cc @williamhyun too because he is a release manager of ORC 1.9.4.

**Pull request closed without merging**
