### PR TITLE
ORC-377: [c++] Add SnappyCompressionStream

### PR DESCRIPTION
**Pull request by czxrrr**
Currently ORC C++ only support writing with Zlib compression
This branch aims to add support for Snappy compression

### CODE REVIEW

**Comment by majetideepak** [comment]
Can you add some tests for this?

**Comment by mathyingzhou** [comment]
Can we reopen the pull request? We are interested in adding the tests and getting it into ORC since my ongoing Arrow2ORC binder won’t be used that much if Snappy write is not supported in the ORC C++ lib.

**Comment by mathyingzhou** [comment]
Now I have time to work on that since I have finished the C++/Python ORC writer in Arrow.

**Comment by pgaref** [comment]
Hey @majetideepak thanks for taking this up! 
Looks that this has been inactive for a while, feel free to open a new PR

**Comment by majetideepak** [comment]
@mathyingzhou feel free to re-open this PR.

**Comment by noirello** [comment]
This PR is dormant for a while now. I could open a new one for adding Snappy compression, if it's okay with everyone.
The task looks very similar to the LZ4 compression that I created recently.

**Comment by mathyingzhou** [comment]
@noirello Sure! I have three more Arrow issues to cover before I can work on this. It will be nice if you can do it this month. Otherwise I will.

**Pull request closed without merging**
