### PR TITLE
ORC-1080: Remove `.travis.yml`

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

This PR aims to remove Travis CI from Apache ORC CIs.

### Why are the changes needed?

In these days, Travis CI takes 4 or more hours to run.

ORC-1079 already provides the same test coverage in GitHub Action. So, we can remove `Travis CI`. safely.

### How was this patch tested?

Travis CI should not be invoked in this PR.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
cc @guiyanakuang and @williamhyun

**Review by williamhyun — APPROVED** [review]
+1 LGTM

**Comment by dongjoon-hyun** [comment]
Thank you, @williamhyun !

**Comment by dongjoon-hyun** [comment]
I backported this to branch-1.7.

**Pull request merged**
