### PR TITLE
MINOR: Fix Union stream kinds in spec

### PR DESCRIPTION
**Pull request by Jefffrey**
Minor typo fix

### CODE REVIEW

**Comment by deshanxiao** [comment]
Thank you @Jefffrey  Good catch! 

Here is the code:
https://github.com/apache/orc/blob/513922af6c1d1a07e632a03231d5b546eeafb26e/java/core/src/java/org/apache/orc/impl/writer/UnionTreeWriter.java#L50

**Comment by deshanxiao** [comment]
@Jefffrey Could you please check ORCv0 and ORCv2 and update them? Thank you.

cc @dongjoon-hyun

**Comment by Jefffrey** [comment]
Sure thing, done :+1:

**Review by deshanxiao — APPROVED** [review]

**Review by wgtmac — APPROVED** [review]

**Comment by deshanxiao** [comment]
Merged to main. Thanks @Jefffrey @wgtmac !

**Pull request closed without merging**
