### PR TITLE
ORC-156

### PR DESCRIPTION
**Pull request by jaimess**
added basic pojo writing support
TestColumnStatistics and TestColumnStatisticsImpl fixed timezone issues

some doubts about package structure, any hint would be appreciated.

added commons.lang3, should I update existing commons.lang to common.lang3 o implement myself the provided functionalty?

### CODE REVIEW

**Comment by omalley** [comment]
I haven't gone through the details yet, but I took the liberty of moving it from core into mapreduce, which is where the other object level shim is. I also renamed the package to pojo instead of pojowriter on the hope that you'll do a PojoReader at some point.

Take a look at https://github.com/omalley/orc/commit/e79b5bcf3c46f0f0e16bf51f5e8c615cf849acfa

**Comment by jaimess** [comment]
Changes are fine. I'm a bit busy at the moment but I think I could write a reader within the next weeks.

**Comment by jaimess** [comment]
Are your changes in any branch I can fork or should I add the reader code in this PR?

**Comment by omalley** [comment]
Oh, sorry, it is at https://github.com/omalley/orc/tree/pr/101

**Pull request closed without merging**
