### PR TITLE
ORC-805: Add .asf.yaml for Apache ORC website publishing

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### What changes were proposed in this pull request?

According to the announcement, we need to add this to our website branch before July 1st.
- https://github.com/apache/infrastructure-website/blob/asf-site/.asf.yaml

### Why are the changes needed?

To comply ASF Git Web site publishing change.

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
BTW, `appveyor` seems to be broken for some other irrelevant reasons.

**Comment by pgaref** [comment]
Thanks for taking care of this @dongjoon-hyun !
Seems like these changes have to be part of the asf-site branch right?

```
the .asf.yaml file MUST be present at the
root of the file system in the branch you wish to publish. T
```

From another apache project: https://github.com/apache/struts-site/blob/asf-site/.asf.yaml

PS: not sure we want to stage the same branch either, we could probably have a new asf-staging branch that has all the latest changes.

**Comment by dongjoon-hyun** [comment]
Yes, this PR is made for `asf-site` branch.
> Seems like these changes have to be part of the asf-site branch right?

Is it just a question or some request, @pgaref ?

**Review by pgaref — APPROVED** [review]

**Comment by pgaref** [comment]
> Yes, this PR is made for `asf-site` branch.
> 
> > Seems like these changes have to be part of the asf-site branch right?
> 
> Screen Shot 2021-06-03 at 9 46 50 AM
> 
> Is it just a question or some request, @pgaref ?

+1 from my side @dongjoon-hyun ! Somehow though the PR was for master, apologies

**Comment by dongjoon-hyun** [comment]
Thank you, @pgaref !

**Pull request merged**
