### PR TITLE
ORC-674: Update docker files

### PR DESCRIPTION
**Pull request by pgaref**
- added docker files for ubuntu 20 with and without clang
 - remove debian 8, and ubuntu 14

(cherry picked from commit 7275ceb8cce0a7316daa357e632fcf4bb21501c8)

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
+1, late LGTM. Thanks, @pgaref .

**Comment by dongjoon-hyun** [comment]
Hi, @pgaref . Did you merge and reset the branch? I cannot see this in `branch-1.6`.

**Comment by pgaref** [comment]
Hey @dongjoon-hyun  -- yeah it was missing the original PR and proper signature so opened #578  instead

**Comment by dongjoon-hyun** [comment]
Got it. No problem~ :)

**Pull request merged**
