### PR TITLE
ORC-880: Reduce Visibility of DictionaryUtils

### PR DESCRIPTION
**Pull request by belugabehr**
### What changes were proposed in this pull request?
Reduce visibility of class `DictionaryUtils`.

### Why are the changes needed?
Prevent a situation where an external user has a dependency on this utility class and therefore the internals cannot change.

### How was this patch tested?
No changes to functionality.  Use existing unit tests.

### CODE REVIEW

**Review by dongjoon-hyun — CHANGES_REQUESTED** [review]
+1 for the intention, but -1 for this minor PR change because it's not worth of doing this.

In the same `impl` directory, we have many `public` Utils classes.
```
$ ls *Utils.java
CryptoUtils.java        DictionaryUtils.java    ParserUtils.java        SerializationUtils.java Utf8Utils.java
DateUtils.java          OrcAcidUtils.java       RecordReaderUtils.java  TypeUtils.java
```

**Comment by belugabehr** [comment]
@dongjoon-hyun Would you rather I abandon this effort altogether or apply this same change to all the `util` classes?

**Comment by dongjoon-hyun** [comment]
We cannot hide all of them because it's an unnecessarily breaking change. At 1.7.0, we already recovered many things to help the downstreams' migration. Although they are designed to be internal, someone use them. So, I'd rather close ORC-880 as 'Won't Do'.

BTW, I really agree with your architectural design mind and your intention here. Sorry for not accepting your efforts, @belugabehr .

**Comment by dongjoon-hyun** [comment]
Thank you for closing this, @belugabehr .

**Pull request closed without merging**
